'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, AudioLines, BookOpen, Check, CircleHelp, FileText, Globe, Headphones, Info, Mic, Play, Plus, Save, Send, ShieldCheck, Sparkles, Trash2, UserRound } from 'lucide-react';
import Shell from './Shell';
import { apiFetch } from './api-client';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
const STEPS = ['Basics', 'Voice', 'Knowledge', 'Behavior', 'Test'];
const languageChoices = ['English (India)', 'Hindi', 'Telugu', 'Tamil', 'Kannada', 'Malayalam', 'Marathi'];
const starter = { name: '', purpose: '', role: 'Customer support', company: 'Acme Support', instructions: '', languages: ['English (India)'], fallbackLanguage: 'English (India)', detectCallerLanguage: true, voice: 'Aarav', speakingSpeed: 'Natural', knowledgeSources: [], actions: { accountLookup: false, supportTicket: false }, greeting: 'Welcome to Acme Support. How can I help you today?', style: 'Concise and helpful', unanswered: 'Ask to connect with a person', endOfCall: 'Summarize the outcome', silenceSeconds: 8, maxCallMinutes: 15, confirmTicket: true };

function Field({ label, children, hint }) { return <label className="field"><span className="field-label">{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
function Switch({ checked, onChange, label }) { return <label className="switch-row"><span>{label}</span><input type="checkbox" checked={Boolean(checked)} onChange={e => onChange(e.target.checked)}/><i aria-hidden="true"/></label>; }
function Card({ title, subtitle, children, icon: Icon }) { return <section className="form-card"><div className="card-header">{Icon && <span className="heading-icon"><Icon size={21}/></span>}<div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div></div>{children}</section>; }

export default function AgentWizard({ id }) {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [agentId, setAgentId] = useState(id || null);
  const [agent, setAgent] = useState(starter);
  const [loading, setLoading] = useState(Boolean(id));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [sourceKind, setSourceKind] = useState('website');
  const [sourceLabel, setSourceLabel] = useState('');
  const [sampleText, setSampleText] = useState('');
  const [sampleResponse, setSampleResponse] = useState('');
  const set = (key, value) => setAgent(current => ({ ...current, [key]: value }));
  useEffect(() => { const requested = Number(new URLSearchParams(window.location.search).get('step')); if (Number.isInteger(requested) && requested >= 0 && requested <= 4) setStep(requested); }, []);
  useEffect(() => { if (!id) return; apiFetch(`${API}/api/voice-agents/${id}`).then(async r => { if (!r.ok) throw Error('Unable to load this agent.'); return r.json(); }).then(v => setAgent({ ...starter, ...v, actions: { ...starter.actions, ...v.actions } })).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [id]);
  async function persist(complete = false) {
    if (!agent.name.trim()) { setError('Enter an agent name in Basics before saving.'); setStep(0); return false; }
    setError(''); setNotice(''); setSaving(true);
    try {
      const endpoint = agentId ? `${API}/api/voice-agents/${agentId}` : `${API}/api/voice-agents`;
      const response = await apiFetch(endpoint, { method: agentId ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(agent) });
      const result = await response.json();
      if (!response.ok) throw Error(result.error || 'Could not save this agent.');
      setAgentId(result._id);
      if (complete) {
        const readyResponse = await apiFetch(`${API}/api/voice-agents/${result._id}/complete`, { method: 'POST' });
        const ready = await readyResponse.json();
        if (!readyResponse.ok) throw Error(ready.error || 'Could not complete this agent.');
        router.push('/voice-agents');
      } else { setNotice('Draft saved.'); if (!id) window.history.replaceState(null, '', `/voice-agents/${result._id}/edit`); }
      return true;
    } catch (e) { setError(e.message); return false; }
    finally { setSaving(false); }
  }
  async function next() { if (step === 0 && !agent.name.trim()) { setError('Agent name is required.'); return; } if (step < 4) { if (!await persist()) return; setStep(step + 1); setNotice(''); } }
  function addSource() { if (!sourceLabel.trim()) return; const text = sourceLabel.trim(); set('knowledgeSources', [...agent.knowledgeSources, { label: text, kind: sourceKind, ...(sourceKind === 'website' ? { url: text } : { content: text }), status: ['website','document'].includes(sourceKind)?'configured':'ready' }]); setSourceLabel(''); }
  function toggleLanguage(language) { const exists = agent.languages.includes(language); if (exists && agent.languages.length <= 1) return; const languages = exists ? agent.languages.filter(l => l !== language) : [...agent.languages, language]; setAgent(current => ({ ...current, languages, fallbackLanguage: languages.includes(current.fallbackLanguage) ? current.fallbackLanguage : languages[0] })); }
  function speak(text){if(typeof window!=='undefined'&&'speechSynthesis'in window){window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=agent.fallbackLanguage==='Telugu'?'te-IN':agent.fallbackLanguage==='Hindi'?'hi-IN':'en-IN';utterance.rate=agent.speakingSpeed==='Fast'?1.13:agent.speakingSpeed==='Slow'?.85:.98;window.speechSynthesis.speak(utterance)}else setError('Browser speech playback is unavailable.');}
  async function previewAnswer(question=sampleText){if(!question.trim())return;try{if(!agentId){setSampleResponse('Save a draft first so the demo engine can read your knowledge sources.');return}const response=await apiFetch('/api/demo/voice/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agentId,question})});const value=await response.json();if(!response.ok)throw Error(value.error||'Preview failed');setSampleResponse(value.answer);speak(value.answer)}catch(error){setSampleResponse(error.message)}}
  async function runDemoTest(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(track=>track.stop());await previewAnswer(sampleText.trim()||'How do I install the widget?')}catch{setSampleResponse('Microphone permission was denied. You can still type a question below to test the FAQ answer.')}}
  if (loading) return <Shell><p className="loading">Loading voice agent…</p></Shell>;
  return <Shell><Link href="/voice-agents" className="back-link"><ArrowLeft size={17}/> Back to voice agents</Link><div className="wizard-heading"><div><p className="eyebrow">VOICE AGENT SETUP</p><h1>{agentId ? agent.name || 'Edit voice agent' : 'Create your voice agent'}</h1><p className="muted">Set up an AI voice agent for natural phone and web conversations.</p></div><span className="status draft">● {agent.status === 'ready' ? 'Ready' : 'Draft'}</span></div>
    <div className="steps" aria-label="Voice agent setup steps">{STEPS.map((label, index) => <button className={`step ${index === step ? 'current' : ''} ${index < step ? 'complete' : ''}`} key={label} onClick={() => setStep(index)}><span>{index < step ? <Check size={18}/> : index + 1}</span><strong>{label}</strong></button>)}</div>
    {error && <p className="form-feedback error" role="alert">{error}</p>}{notice && <p className="form-feedback success" role="status">{notice}</p>}
    {step === 0 && <div className="wizard-columns"><Card title="Agent basics" subtitle="Give your agent a clear identity and purpose."><div className="field-stack"><Field label="Agent name *"><input value={agent.name} onChange={e => set('name', e.target.value)} maxLength={90} placeholder="Website Support"/></Field><Field label="Purpose"><textarea rows="3" value={agent.purpose} onChange={e => set('purpose', e.target.value)} placeholder="Answer support calls and connect customers to a person when needed."/></Field><Field label="Agent role"><select value={agent.role} onChange={e => set('role', e.target.value)}><option>Customer support</option><option>Sales enquiries</option><option>Appointment scheduling</option><option>Custom</option></select></Field><Field label="Company"><input value={agent.company} onChange={e => set('company', e.target.value)}/></Field><Field label="Instructions"><textarea rows="3" value={agent.instructions} onChange={e => set('instructions', e.target.value)} placeholder="Help customers with setup, pricing and account questions. Escalate unresolved issues."/></Field></div></Card><Card title="Voice agent preview" subtitle="See how your agent will introduce itself and respond."><div className="preview-chat"><span className="preview-orb"><AudioLines size={36}/></span><h3>{agent.name || 'Your voice agent'}</h3><p>{agent.company || 'Your company'}</p><div className="bubble">{agent.greeting}</div><div className="bubble reply">I need help with my account setup.</div><div className="preview-input">Sample conversation preview <Send size={17}/></div></div></Card></div>}
    {step === 1 && <div className="wizard-columns"><div className="column-stack"><Card icon={Globe} title="Language coverage" subtitle="Choose the languages your voice agent can speak."><div className="language-options">{languageChoices.map(language => <button key={language} className={`language-choice ${agent.languages.includes(language) ? 'chosen' : ''}`} onClick={() => toggleLanguage(language)}>{agent.languages.includes(language) ? <Check size={17}/> : <Plus size={17}/>} {language}</button>)}</div><div className="subtle-divider"/><Field label="Fallback language"><select value={agent.fallbackLanguage} onChange={e => set('fallbackLanguage', e.target.value)}>{agent.languages.map(language => <option key={language}>{language}</option>)}</select></Field></Card><Card icon={Mic} title="Voice identity" subtitle="Choose a voice and a speaking speed.">{['Aarav', 'Maya'].map(voice => <label key={voice} className={`voice-option ${agent.voice === voice ? 'chosen' : ''}`}><input type="radio" name="voice" checked={agent.voice === voice} onChange={() => set('voice', voice)}/><span className="voice-play"><Play size={18}/></span><span><strong>{voice}</strong><small>{voice === 'Aarav' ? 'Warm & clear' : 'Calm & friendly'}</small></span><span className="voice-option-end">Voice option</span></label>)}<Field label="Speaking speed"><select value={agent.speakingSpeed} onChange={e => set('speakingSpeed', e.target.value)}><option>Slow</option><option>Natural</option><option>Fast</option></select></Field></Card></div><Card icon={Headphones} title="Voice preview" subtitle="Selected voice and language settings."><div className="voice-preview-box"><div className="bubble">Hello! How can I help you today?</div><div className="wave-line"><AudioLines size={47}/><span>{agent.voice} · {agent.speakingSpeed}</span></div></div><div className="callout"><Info size={19}/> Caller language can be detected automatically. This is a settings preview; voice samples are available when audio service is connected.</div><Switch label="Detect caller language" checked={agent.detectCallerLanguage} onChange={v => set('detectCallerLanguage', v)}/></Card></div>}
    {step === 2 && <div className="wizard-columns"><Card icon={BookOpen} title="Give your agent the right knowledge" subtitle="Add sources the agent can use to answer questions."><div className="source-tiles">{[['website','Website',Globe],['document','Document',FileText],['faq','FAQs',CircleHelp],['business','Business details',Info]].map(([kind,label,Icon]) => <button className={`source-tile ${sourceKind === kind ? 'chosen' : ''}`} key={kind} onClick={() => setSourceKind(kind)}><Icon size={21}/><strong>{label}</strong></button>)}</div><div className="source-add"><input value={sourceLabel} onChange={e => setSourceLabel(e.target.value)} placeholder={sourceKind === 'website' ? 'https://example.com/help' : sourceKind === 'faq' ? 'Question and answer (text)' : sourceKind === 'document' ? 'Document name (file uploads in next phase)' : 'Business information'} aria-label="Knowledge source"/><button className="button primary" onClick={addSource}><Plus size={17}/> Add source</button></div><p className="helper-text">Source labels are saved now. URL crawling, document upload and retrieval indexing are added with the AI integration.</p><h3 className="section-label">Added knowledge sources</h3><div className="source-list">{agent.knowledgeSources.length ? agent.knowledgeSources.map((source, index) => <div className="source-row" key={`${source.label}-${index}`}><span>{source.label}</span><span className="pill">{source.kind}</span><button aria-label={`Remove ${source.label}`} onClick={() => set('knowledgeSources', agent.knowledgeSources.filter((_, i) => i !== index))}><Trash2 size={17}/></button></div>) : <p className="muted">No sources added yet.</p>}</div><h3 className="section-label">Actions</h3><Switch label="Look up account status" checked={agent.actions.accountLookup} onChange={v => set('actions', { ...agent.actions, accountLookup: v })}/><Switch label="Create support ticket" checked={agent.actions.supportTicket} onChange={v => set('actions', { ...agent.actions, supportTicket: v })}/><p className="helper-text">Action switches store intent. They cannot perform account lookups or create tickets until secure integrations are configured.</p></Card><Card icon={Sparkles} title="Test an answer" subtitle="Preview your configured knowledge settings."><div className="test-panel"><input value={sampleText} onChange={e => setSampleText(e.target.value)} placeholder="How do I install the widget?" aria-label="Sample question"/><button className="button secondary" onClick={()=>previewAnswer()}>Preview answer settings</button>{sampleResponse && <p className="callout">{sampleResponse}</p>}</div></Card></div>}
    {step === 3 && <div className="wizard-columns"><Card icon={Mic} title="Shape the call conversation" subtitle="Configure how the agent speaks and handles edge cases."><div className="field-stack"><Field label="Greeting"><input value={agent.greeting} maxLength={400} onChange={e => set('greeting', e.target.value)}/></Field><div className="field"><span className="field-label">Conversation style</span><div className="radio-choices">{['Concise and helpful','Detailed'].map(style => <label key={style}><input type="radio" checked={agent.style === style} onChange={() => set('style', style)}/>{style}</label>)}</div></div><Field label="When the agent cannot answer"><select value={agent.unanswered} onChange={e => set('unanswered', e.target.value)}><option>Ask to connect with a person</option><option>Offer a callback</option><option>End politely</option></select></Field><Field label="End of call"><select value={agent.endOfCall} onChange={e => set('endOfCall', e.target.value)}><option>Summarize the outcome</option><option>End without a summary</option></select></Field></div></Card><div className="column-stack"><Card icon={ShieldCheck} title="Call safeguards" subtitle="Set limits and fallbacks for a good caller experience."><div className="field-stack"><Field label="Silence prompt after (seconds)"><input type="number" min="3" max="30" value={agent.silenceSeconds} onChange={e => set('silenceSeconds', Number(e.target.value))}/></Field><Field label="Maximum call length (minutes)"><input type="number" min="1" max="120" value={agent.maxCallMinutes} onChange={e => set('maxCallMinutes', Number(e.target.value))}/></Field><Switch label="Confirm before creating a ticket" checked={agent.confirmTicket} onChange={v => set('confirmTicket', v)}/></div></Card><Card icon={UserRound} title="Human handoff" subtitle="When a caller asks for a person or AI cannot resolve the issue."><p className="muted">Routing, business hours and callback options are configured in the Voice Widget. Saving an agent does not publish a calling endpoint.</p></Card></div></div>}
    {step === 4 && <div className="wizard-columns"><Card icon={AudioLines} title="Test and save your voice agent" subtitle="Review the setup before connecting it to a Voice Widget."><div className="test-hero"><span className="test-orb"><AudioLines size={51}/></span><h3>{agent.name || 'Your voice agent'}</h3><p>{agent.company}</p><span className="status ready">● Configuration ready</span><button className="button primary" onClick={runDemoTest}><Mic size={18}/> Start demo test call</button><p className="helper-text">Uses browser speech and local FAQ responses. No real provider call.</p></div></Card><div className="column-stack"><Card title="Readiness checklist" subtitle="Review the settings that will be saved."><div className="checklist">{[['Basics', `${agent.company} · ${agent.name || 'Name needed'}`],['Voice', `${agent.languages.join(', ')} · ${agent.voice}`],['Knowledge', `${agent.knowledgeSources.length} sources configured`],['Conversation rules', `${agent.style} · ${agent.maxCallMinutes} min max`],['Human handoff', 'Set up later in Voice Widget']].map(([title, detail], index) => <div key={title} className="check-item"><span className={index === 4 ? 'check-info' : 'check-icon'}>{index === 4 ? <Info size={17}/> : <Check size={17}/>}</span><span><strong>{title}</strong><small>{detail}</small></span></div>)}</div></Card><Card icon={Info} title="How it works"><p className="muted">Saving this agent keeps it in your workspace. Connect it to a Voice Widget to publish it on your website.</p></Card></div></div>}
    {step===1&&<div className="demo-control"><span className="demo-control-tag">BROWSER AUDIO PREVIEW</span><button className="button secondary" onClick={()=>speak('Hello! How can I help you today?')}><Play size={16}/> Hear greeting in your browser</button><span className="helper-text">Device TTS preview; Aarav/Maya branded voices require Paluku TTS integration.</span></div>}
    {step===4&&<div className="demo-control"><span className="demo-control-tag">INTERACTIVE DEMO</span><h3>Try a sample question</h3><div className="demo-question"><input value={sampleText} onChange={e=>setSampleText(e.target.value)} placeholder="How do I install the widget?" aria-label="Demo question"/><button className="button primary" onClick={()=>previewAnswer()}>Ask demo agent</button></div>{sampleResponse&&<p className="demo-result">{sampleResponse}</p>}<p className="helper-text">Demo answers use local FAQ keyword matching and browser audio. No real call is placed.</p></div>}
    <div className="wizard-footer"><div>{step > 0 && <button className="button secondary" onClick={() => { setStep(step - 1); setError(''); }}><ArrowLeft size={17}/> Previous</button>}</div><div className="footer-actions"><button disabled={saving} onClick={() => persist()} className="button secondary"><Save size={17}/>{saving ? 'Saving…' : 'Save draft'}</button>{step < 4 ? <button className="button primary" onClick={next}>Continue to {STEPS[step + 1].toLowerCase()} <ArrowRight size={18}/></button> : <button disabled={saving} onClick={() => persist(true)} className="button primary">Save voice agent <ArrowRight size={18}/></button>}</div></div>
  </Shell>;
}
