'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Activity, ArrowLeft, ArrowRight, AudioLines, BookOpen, Check, CheckCircle2, CircleHelp, Clock3, FileText, Headphones, Mic2, Phone, Play, Plus, Save, ShieldCheck, Sparkles, Volume2 } from 'lucide-react';
import { apiFetch } from './api-client';
import DemoControls from './DemoControls';

const tabs=[['Overview','/voice-agents'],['Instructions','/flow/34'],['Knowledge','/flow/35'],['Actions','/flow/36'],['Advanced','/flow/37'],['Quality','/flow/38'],['Versions','/flow/39'],['Inbound','/flow/40'],['Performance','/flow/41']];
const title={34:'Agent instructions & prompt',35:'Knowledge sources',36:'Actions & integrations',37:'Advanced voice behaviour',38:'Call data & quality rules',39:'Test, publish & versions',40:'Phone number & inbound routing',41:'Voice agent performance'};
function Field({field,value,onChange,agents}){
  const base={value:value??'',onChange:e=>onChange(field.type==='switch'?e.target.checked:e.target.value)};
  if(field.type==='switch')return <label className="studio-toggle"><span>{field.label}</span><input type="checkbox" checked={Boolean(value)} onChange={base.onChange}/></label>;
  if(field.type==='select'||field.type==='agent')return <label className="field"><span className="field-label">{field.label}</span><select {...base}><option value="">Select {field.label.toLowerCase()}</option>{(field.type==='agent'?agents.map(item=>item.name):field.options).map(option=><option key={option}>{option}</option>)}</select></label>;
  return <label className="field"><span className="field-label">{field.label}</span>{field.type==='textarea'?<textarea {...base} rows={field.label.includes('instructions')?6:3}/>:<input {...base} type={field.type||'text'}/>}</label>;
}
function Card({icon:Icon,heading,sub,children}){return <section className="studio-card"><div className="studio-card-head"><span><Icon size={21}/></span><div><h2>{heading}</h2>{sub&&<p>{sub}</p>}</div></div>{children}</section>}

export default function AgentStudio({number,config,form,setForm,agents,records,record,feedback,working,onSave,onUpdate}){
  const [question,setQuestion]=useState('How do I install the widget?');
  const [answer,setAnswer]=useState('');
  const [testing,setTesting]=useState(false);
  const selected=agents.find(item=>item.name===form['Voice agent'])||agents[0];
  const update=(label,value)=>setForm(current=>({...current,[label]:value}));
  const renderFields=(fields)=>fields.map(field=><Field key={field.label} field={field} value={form[field.label]} onChange={value=>update(field.label,value)} agents={agents}/>);
  async function test(){setTesting(true);try{const response=await apiFetch('/api/demo/voice/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agentId:selected?._id,question})});const data=await response.json();if(!response.ok)throw Error(data.error);setAnswer(data.answer)}catch(error){setAnswer(error.message)}finally{setTesting(false)}}
  const save=()=>onSave({advance:false});
  const next=()=>onSave({advance:number!==41,status:number===40?'active':undefined});
  const performance=number===41;
  return <div className="studio-page"><Link href="/voice-agents" className="studio-back"><ArrowLeft size={17}/> Back to voice agents</Link><div className="studio-identity"><span className="studio-identity-icon"><Headphones size={27}/></span><div><h1>{performance?'Voice agent performance · demo':selected?.name||'Website Support'}</h1><p>{selected?.company||'Acme Support'} · {selected?.purpose||'AI voice support'}</p></div><span className={`status ${selected?.status==='ready'?'ready':'draft'}`}>● {selected?.status||'Draft'}</span>{!performance&&<button className="button primary" disabled={working} onClick={save}><Save size={17}/> Save draft</button>}</div><nav className="studio-nav" aria-label="Voice agent settings">{tabs.map(([name,href])=><Link key={name} href={href} className={href===`/flow/${number}`?'active':''}>{name}</Link>)}</nav><div className="studio-intro"><div><h2>{title[number]}</h2><p>{performance?'Workspace sample calls are not attributed to an individual AI agent.':config.caption}</p></div>{number===39&&<span className="status draft">Draft version</span>}</div>{feedback&&<p role="status" className="flow-alert">{feedback}</p>}
  {number===34&&<div className="studio-columns"><div><Card icon={Mic2} heading="Opening statement" sub="The first thing your assistant says when a call starts."><div className="studio-form">{renderFields(config.fields.filter(f=>f.label==='Voice agent'))}<label className="field"><span className="field-label">Opening statement</span><textarea rows={3} value={form['Opening statement']??selected?.greeting??''} onChange={e=>update('Opening statement',e.target.value)}/></label><div className="studio-help">Bot speaks first · available only in the demo preview</div></div></Card><Card icon={FileText} heading="System instructions" sub="Define role, goals, boundaries and human handoff."><div className="studio-form">{renderFields(config.fields.filter(f=>f.label!=='Voice agent'))}</div></Card></div><Card icon={Sparkles} heading="Test your agent’s instructions" sub="Ask a sample question to preview the FAQ response."><div className="studio-sample"><span>Customer</span><p>{question}</p><span>{selected?.name||'AI'} · preview</span><p className="studio-sample-answer">{answer||'Ask a question to see how the configured knowledge responds.'}</p></div><div className="studio-question"><input value={question} onChange={e=>setQuestion(e.target.value)} aria-label="Test question"/><button className="button primary" disabled={testing} onClick={test}>{testing?'Testing…':'Test prompt'} <ArrowRight size={15}/></button></div><div className="studio-help">FAQ keyword preview; live spoken AI needs the voice provider.</div></Card></div>}
  {number===35&&<div className="studio-columns"><div><Card icon={BookOpen} heading="Knowledge sources" sub="Manage information that your agent can use to answer callers."><div className="studio-form">{renderFields(config.fields)}</div><div className="studio-source-list"><h3>Added sources</h3>{selected?.knowledgeSources?.map((source,i)=><div className="studio-source" key={source._id||i}><FileText size={20}/><span><strong>{source.label}</strong><small>{source.kind||'Document'}</small></span><em className={source.status==='ready'?'ready':''}>{source.status||'Configured'}</em></div>)}{!selected?.knowledgeSources?.length&&<p>No sources yet. Add a FAQ or website URL.</p>}</div></Card></div><div><Card icon={Sparkles} heading="Test a question" sub="Check which source your agent uses."><div className="studio-question"><input value={question} onChange={e=>setQuestion(e.target.value)} aria-label="Knowledge test question"/><button className="button primary" onClick={test} disabled={testing}>Ask</button></div><p className="studio-sample-answer" role="status">{answer||'Enter a question and ask the demo agent.'}</p></Card><DemoControls number={35} record={record} form={form} agents={agents} onUpdate={onUpdate}/></div></div>}
  {number===36&&<div className="studio-columns"><div><Card icon={ShieldCheck} heading="Actions & integrations" sub="Choose what the agent is allowed to do during calls."><div className="studio-action"><Phone size={19}/><div><strong>Transfer to a human</strong><small>Route callers to the support team when needed.</small></div><span>Configured in Voice Widget</span></div><div className="studio-form">{renderFields(config.fields)}</div></Card></div><Card icon={Activity} heading="Configure an action" sub="External account and ticket actions need verified server credentials."><div className="studio-notice">The demo stores action settings. It does not call your account system or create live tickets.</div><div className="studio-details"><div><span>Current agent</span><strong>{selected?.name||'Select agent'}</strong></div><div><span>Account lookup</span><strong>{form['Account lookup']?'Enabled · needs connection':'Off'}</strong></div><div><span>Ticket creation</span><strong>{form['Ticket creation']?'Enabled · needs connection':'Off'}</strong></div></div></Card></div>}
  {number===37&&<div className="studio-columns"><Card icon={Volume2} heading="Advanced voice behaviour" sub="Control interruptions, silence and fallback language."><div className="studio-form">{renderFields(config.fields)}</div><div className="studio-notice">A real provider decides the actual silence detection and interruption timing.</div></Card><Card icon={AudioLines} heading="Simulation preview" sub="See an example of your configured response flow."><div className="studio-timeline"><p><b>1</b> Caller speaks in {form['Fallback language']||selected?.fallbackLanguage||'English (India)'}</p><p><b>2</b> Assistant checks the knowledge source</p><p><b>3</b> If unresolved, request human handoff</p></div><button className="button secondary" onClick={test}><Play size={16}/> Preview response</button>{answer&&<p className="studio-sample-answer">{answer}</p>}</Card></div>}
  {number===38&&<div className="studio-columns"><Card icon={FileText} heading="Call data & quality rules" sub="Choose which caller information and call artifacts are stored."><div className="studio-form">{renderFields(config.fields)}</div><div className="studio-notice">Storage preferences apply to the demo record. Configure consent, retention and deletion before live calls.</div></Card><Card icon={ShieldCheck} heading="Conversation quality criteria" sub="Review handoff and outcome completeness."><div className="studio-timeline"><p><b>✓</b> Ask for consent before saving caller details</p><p><b>✓</b> Escalate unresolved requests</p><p><b>✓</b> Save a post-call outcome</p></div><div className="studio-help">Only local preview rules are available until a QA service is connected.</div></Card></div>}
  {number===39&&<div className="studio-columns"><Card icon={CheckCircle2} heading="Draft v3 is ready to test" sub="Review changes before saving a new draft."><div className="studio-checklist">{[['Prompt',selected?.instructions],['Knowledge',`${selected?.knowledgeSources?.length||0} sources`],['Actions',selected?.actions?'Configured':'Not configured'],['Voice',selected?.voice],['Human handoff','Configure in Voice Widget']].map(([label,value])=><div key={label}><Check size={18}/><span>{label}</span><strong>{value?'Ready':'Review'}</strong></div>)}</div><div className="studio-form">{renderFields(config.fields)}</div></Card><Card icon={Mic2} heading="Test call console" sub="Preview answer and handoff with simulated audio."><div className="studio-question"><input value={question} onChange={e=>setQuestion(e.target.value)} aria-label="Test call question"/><button className="button primary" onClick={test} disabled={testing}>Start test</button></div><p className="studio-sample-answer">{answer||'The test stays in your browser; no phone number is dialed.'}</p><div className="studio-notice">Save draft keeps the current live widget unchanged.</div></Card></div>}
  {number===40&&<div className="studio-columns"><Card icon={Phone} heading="Connect an inbound number" sub="Choose the business number and voice agent for incoming calls."><div className="studio-form">{renderFields(config.fields)}</div><div className="studio-notice">This route stays in demo mode until a telephony provider verifies the number and sends signed call webhooks.</div></Card><Card icon={Activity} heading="Call path" sub="Preview the customer journey when a provider is connected."><div className="studio-timeline"><p><b>1</b> Caller dials {form['Business phone number']||'+91 business number'}</p><p><b>2</b> {form.Agent||selected?.name||'Voice agent'} greets them</p><p><b>3</b> AI requests a human if necessary</p><p><b>4</b> An unavailable team offers callback</p></div><DemoControls number={42} record={record} form={form} agents={agents} onUpdate={onUpdate}/></Card></div>}
  {number===41&&<><div className="studio-performance">{[['Total calls',records.length,Phone],['Human handoffs',records.filter(r=>r.data?.assignedAgent).length,Headphones],['Completed',records.filter(r=>r.status==='ended').length,CheckCircle2],['Waiting',records.filter(r=>r.status==='waiting').length,Clock3]].map(([label,value,Icon])=><div key={label}><Icon size={22}/><span>{label}</span><strong>{value}</strong></div>)}</div><div className="studio-columns"><Card icon={Activity} heading="Call volume" sub="Demo calls in this workspace."><div className="studio-chart">{[4,7,5,9,8,12,11,15,13,16,14,18].map((n,i)=><span key={i} style={{height:`${n*4}%`}}/>)}</div></Card><Card icon={Phone} heading="Recent calls" sub="Open history to review transcript and outcome.">{records.slice(0,5).map(item=><div key={item._id} className="studio-source"><Phone size={18}/><span><strong>{item.title}</strong><small>{item.data?.screen_14?.['Issue summary']||'Voice request'}</small></span><em>{item.status}</em></div>)}<Link className="button secondary" href="/flow/17">View call history</Link></Card></div></>}
  {!performance&&<footer className="studio-footer"><Link className="button secondary" href={number===34?'/voice-agents':`/flow/${number-1}`}><ArrowLeft size={16}/> Previous</Link><div><button className="button secondary" disabled={working} onClick={save}>Save draft</button><button className="button primary" disabled={working} onClick={next}>{working?'Saving…':number===40?'Save inbound route':number===39?'Save draft version':'Save & continue'} <ArrowRight size={16}/></button></div></footer>}
  </div>;
}
