'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, CalendarDays, Check, CheckCircle2, Clock3, FileSpreadsheet, Megaphone, Phone, PhoneCall, ShieldCheck, UploadCloud, Users } from 'lucide-react';
import { apiFetch } from './api-client';

const stepNames=['Basics & agent','Contacts','Calling settings','Schedule','Review & launch'];
function Field({field,value,onChange,agents}){
  const props={value:value??'',onChange:event=>onChange(field.type==='switch'?event.target.checked:event.target.value)};
  if(field.type==='switch')return <label className="campaign-toggle"><span>{field.label}</span><input type="checkbox" checked={Boolean(value)} onChange={props.onChange}/></label>;
  if(field.type==='agent'||field.type==='select')return <label className="field"><span className="field-label">{field.label}</span><select {...props}><option value="">Select {field.label.toLowerCase()}</option>{(field.type==='agent'?agents.map(a=>a.name):field.options).map(name=><option key={name}>{name}</option>)}</select></label>;
  return <label className="field"><span className="field-label">{field.label}</span>{field.type==='textarea'?<textarea {...props} rows={field.label.includes('Contacts')?7:3}/>:<input {...props} type={field.type||'text'}/>}</label>;
}
function Panel({title,description,children}){return <section className="campaign-wizard-panel"><h2>{title}</h2>{description&&<p>{description}</p>}{children}</section>}
function Summary({record,form,number,agents}){const basics=number===44?form:record?.data?.screen_44||{};const contacts=number===45?form:record?.data?.screen_45||{};const calling=number===46?form:record?.data?.screen_46||{};const schedule=number===47?form:record?.data?.screen_47||{};return <Panel title="Campaign summary" description="Current saved settings and launch prerequisites."><div className="campaign-wizard-summary">{[['Campaign',basics['Campaign name']||record?.title||'Not set'],['Purpose',basics.Purpose||'Not set'],['Voice agent',basics['Voice agent']||'Not selected'],['Contacts',contacts['Contacts (one phone per line)']?`${contacts['Contacts (one phone per line)'].split(/[\n,;]+/).filter(Boolean).length} entered`:'Not uploaded'],['Consent',contacts['Consent source']||'Not recorded'],['Caller number',calling['Verified caller number']||'Not verified'],['Start',schedule['Start date and time']||'Not scheduled']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{number===48&&<div className="campaign-wizard-note">Scheduling saves this campaign for the demo. Only a connected, verified dialer can place real calls.</div>}</Panel>}

export default function CampaignWizard({number,config,record,form,setForm,agents,working,feedback,onSave}){
  const [importMessage,setImportMessage]=useState('');
  const [preview,setPreview]=useState('');
  const [checking,setChecking]=useState(false);
  const update=(label,value)=>setForm(current=>({...current,[label]:value}));
  const rows=String(form['Contacts (one phone per line)']||record?.data?.screen_45?.['Contacts (one phone per line)']||'').split(/[\n,;]+/).map(text=>text.trim()).filter(Boolean);
  const distinct=[...new Set(rows)];const eligible=distinct.filter(phone=>/^\+?[0-9]{10,15}$/.test(phone));
  async function importCsv(event){const file=event.target.files?.[0];if(!file)return;try{if(file.size>2_000_000)throw Error('Maximum CSV size for this preview is 2 MB.');const content=await file.text();const lines=content.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);const header=lines[0]?.toLowerCase().split(',')||[];const phoneIndex=header.findIndex(label=>/phone|mobile|number/.test(label));const phones=(phoneIndex<0?lines:lines.slice(1)).map(line=>line.split(',')[Math.max(0,phoneIndex)]?.replace(/^"|"$/g,'').trim()).filter(Boolean);update('Contacts (one phone per line)',phones.join('\n'));setImportMessage(`${file.name}: ${phones.length} contacts loaded. Check phone numbers and consent before continuing.`)}catch(error){setImportMessage(error.message)}}
  async function check(){if(!record)return setPreview('Save the campaign first, then check eligibility.');setChecking(true);try{const response=await apiFetch(`/api/demo/campaigns/${record._id}/eligibility`);const data=await response.json();if(!response.ok)throw Error(data.error);setPreview(`${data.eligible} eligible · ${data.excluded} excluded · ${data.duplicates} duplicate. These are formatting checks only; external consent and suppression have not been verified.`)}catch(error){setPreview(error.message)}finally{setChecking(false)}}
  const fields=(labels)=>config.fields.filter(f=>labels.includes(f.label)).map(field=><Field key={field.label} field={field} value={form[field.label]} onChange={value=>update(field.label,value)} agents={agents}/>);
  return <div className="campaign-wizard"><Link href="/flow/43" className="studio-back"><ArrowLeft size={17}/> Back to campaigns</Link><div className="studio-identity"><span className="studio-identity-icon"><PhoneCall size={27}/></span><div><h1>{record?.title||form['Campaign name']||'Create campaign'}</h1><p>Outbound voice campaign · Acme Support</p></div><span className={`status ${record?.status==='running'?'ready':'draft'}`}>● {record?.status||'New draft'}</span><button className="button primary" disabled={working} onClick={()=>onSave({advance:false})}>Save draft</button></div><nav className="campaign-wizard-progress" aria-label="Campaign setup steps">{stepNames.map((name,index)=><Link className={index===number-44?'active':index<number-44?'done':''} key={name} href={`/flow/${44+index}`}><span>{index<number-44?<Check size={16}/>:index+1}</span>{name}</Link>)}</nav><div className="campaign-wizard-intro"><div><h2>{config.title}</h2><p>{config.caption}</p></div><span>Step {number-43} of 5</span></div>{feedback&&<div role="status" className="flow-alert">{feedback}</div>}
  <div className="campaign-wizard-grid"><div>
  {number===44&&<><Panel title="Campaign basics" description="Name the campaign and state why recipients are being contacted."><div className="campaign-wizard-fields">{fields(['Campaign name','Purpose','Voice agent','Opening script'])}</div></Panel><Panel title="Test agent" description="Preview a sample greeting with the selected voice agent."><div className="campaign-wizard-agent"><Megaphone size={27}/><span><strong>{form['Voice agent']||'Select a voice agent'}</strong><small>AI agent for this outbound campaign</small></span></div><div className="campaign-wizard-note">Test calls are browser previews until the outbound provider is connected.</div></Panel></>}
  {number===45&&<><Panel title="Upload contacts" description="Import a CSV or enter one phone number per line."><div className="campaign-wizard-upload"><FileSpreadsheet size={28}/><span><strong>Choose a CSV file</strong><small>Phone or mobile column · 2 MB maximum</small></span><label className="button secondary"><UploadCloud size={16}/> Upload CSV<input type="file" accept=".csv,text/csv" onChange={importCsv} hidden/></label></div>{importMessage&&<p className="campaign-wizard-note" role="status">{importMessage}</p>}<div className="campaign-wizard-fields">{fields(['Contacts (one phone per line)','Consent source','Suppress opted-out contacts'])}</div><button className="button secondary" onClick={check} disabled={checking}>{checking?'Checking…':'Check saved eligibility'}</button>{preview&&<p className="campaign-wizard-note" role="status">{preview}</p>}</Panel></>}
  {number===46&&<><Panel title="Caller number & outbound calling pool" description="Use a verified caller ID and reserve capacity for inbound requests."><div className="campaign-wizard-fields">{fields(['Verified caller number','Concurrent campaign calls','Reserved inbound slots','Calls per second'])}</div></Panel><Panel title="Call capacity" description="Review the configured concurrency before launch."><div className="campaign-wizard-tiles"><div><strong>{form['Concurrent campaign calls']||5}</strong><span>Campaign calls</span></div><div><strong>{form['Reserved inbound slots']||2}</strong><span>Reserved inbound</span></div><div><strong>{form['Calls per second']||1}</strong><span>Calls per second</span></div></div><div className="campaign-wizard-note">Actual carrier concurrency requires provider capacity and rate controls.</div></Panel></>}
  {number===47&&<><Panel title="Campaign schedule" description="Choose calling times and a time zone appropriate for your contacts."><div className="campaign-wizard-fields">{fields(['Start date and time','End date and time','Time zone','Maximum retries','Voicemail action'])}</div></Panel><Panel title="Retry policy" description="Demo scheduling stores your settings; it will not call contacts automatically."><div className="campaign-wizard-note"><Clock3 size={18}/> Enforce approved hours, consent, suppression, retry limits and local law when a live dialer is connected.</div></Panel></>}
  {number===48&&<><Panel title="Campaign summary" description="Review all saved settings before scheduling a demo campaign."><div className="campaign-wizard-summary">{[['Name',record?.title],['Agent',record?.data?.screen_44?.['Voice agent']],['Contacts',record?.data?.screen_45?.['Contacts (one phone per line)']?.split(/[\n,;]+/).filter(Boolean).length],['Consent source',record?.data?.screen_45?.['Consent source']],['Caller number',record?.data?.screen_46?.['Verified caller number']],['Start',record?.data?.screen_47?.['Start date and time']]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value||'Missing'}</strong></div>)}</div></Panel><Panel title="Preview & confirm" description="Demo readiness check before saving the campaign schedule."><div className="campaign-wizard-check"><CheckCircle2 size={22}/> Agent and contact settings can be reviewed above.</div><div className="campaign-wizard-note">No calls start when you schedule. The Run demo button on monitoring animates synthetic results only.</div></Panel></>}
  </div><aside><Summary record={record} form={form} number={number} agents={agents}/><Panel title="Eligibility preview" description="Format check for the numbers entered."><div className="campaign-wizard-tiles"><div><strong>{rows.length}</strong><span>Uploaded</span></div><div><strong>{eligible.length}</strong><span>Valid format</span></div><div><strong>{rows.length-eligible.length}</strong><span>Excluded</span></div></div><div className="campaign-wizard-note">Consent, DND and opt-out checks require connected data sources.</div></Panel></aside></div><footer className="studio-footer"><Link className="button secondary" href={number===44?'/flow/43':`/flow/${number-1}`}><ArrowLeft size={16}/> Previous</Link><div><button className="button secondary" onClick={()=>onSave({advance:false})} disabled={working}>Save draft</button><button className="button primary" onClick={()=>onSave({advance:number!==48,status:number===48?'scheduled':undefined})} disabled={working}>{working?'Saving…':number===48?'Schedule demo campaign':'Continue'} <ArrowRight size={16}/></button></div></footer></div>;
}
