'use client';
import { useState } from 'react';
import Link from 'next/link';
import { AudioLines, ArrowLeft, ArrowRight, BookOpen, CalendarDays, CheckCircle2, CircleHelp, Clock3, Headphones, Mail, Mic, Phone, PhoneOff, Search, Send, ShieldCheck, Star, UserRound, Volume2, X } from 'lucide-react';
import { apiFetch } from './api-client';

const icons=[BookOpen,ShieldCheck,AudioLines,Headphones];
const cards=[['Getting started','Set up the account and learn the basics'],['Product guides','Find setup instructions and tutorials'],['Billing & plans','Manage subscription and payments'],['Troubleshooting','Resolve common problems']];
export default function CustomerWidget({number,config,record,form,setForm,onPrimary,onSave,feedback,working,widgetToken,widgetId}) {
  const [stars,setStars]=useState(5);
  const [answer,setAnswer]=useState('');
  const [typing,setTyping]=useState(false);
  const [muted,setMuted]=useState(false);
  const widgetPath=value=>`/flow/${value}${widgetId?`?widget=${encodeURIComponent(widgetId)}`:''}`;
  async function ask(){const question=String(form['Your question']||'').trim();if(!question)return;setTyping(true);try{const response=await apiFetch('/api/demo/widget/answer',{method:'POST',headers:{'Content-Type':'application/json','X-Widget-Session':widgetToken},body:JSON.stringify({question})});const data=await response.json();if(!response.ok)throw Error(data.error);setAnswer(data.answer);if(!muted&&'speechSynthesis'in window){window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(data.answer);utterance.lang='en-IN';window.speechSynthesis.speak(utterance)}}catch(error){setAnswer(error.message)}finally{setTyping(false)}}
  function update(label,value){setForm(current=>({...current,[label]:value}))}
  return <div className="acme-site"><header className="acme-header"><Link href={widgetPath(28)} className="acme-logo"><span className="acme-logo-glyph">◆</span> Acme</Link><nav><span>Products</span><span>Support</span><span>Pricing</span><span>Resources</span></nav><button>Get started</button></header><main className="acme-body"><p className="acme-eyebrow">HELP CENTER</p><h1>Acme Support</h1><p>How can we help you today?</p><div className="acme-search"><Search size={19}/> Search for help articles, guides, and FAQs…</div><div className="acme-cards">{cards.map(([title,description],index)=>{const Icon=icons[index];return <div className="acme-card" key={title}><span><Icon size={21}/></span><strong>{title}</strong><small>{description}</small><span className="acme-more">View articles →</span></div>})}</div><h2>Popular articles</h2>{['How to set up your first agent','Change billing information','Install a widget on your website','Contact support'].map(title=><div className="acme-article" key={title}><BookOpen size={17}/>{title} <span>›</span></div>)}</main>
    <section aria-label="ChatBucket voice widget" className="voice-widget"><div className="widget-top"><strong><span className="widget-small-logo"><AudioLines size={16}/></span> ChatBucket <small>· Acme Support</small></strong><span className="widget-language">English · हिन्दी</span></div><div className="widget-crumb"><span>⌕ Chat</span><span className="widget-crumb-active"><Phone size={13}/> Voice Support</span><span>✦ Help center</span></div><div className="widget-body"><span className="widget-avatar"><AudioLines size={22}/></span><h2>{number===28?'Talk to support':number===29?'Website Support AI':number===30?'Finding a human specialist':number===31?'Priya Sharma joined':number===32?'Request a callback':number===33?'How was your support?':'Inbound phone support'}</h2><p className="widget-subtitle">{number===28?'Hi! How can we help today?':number===29?'AI is speaking · Ask your question':number===30?'The team has your request':number===31?'A support specialist is connected':number===32?'Our team will contact you':number===33?'Your call has ended':'Acme Support · AI voice agent'}</p>
      {number===28&&<><p className="widget-description">Speak naturally with our AI voice agent. Ask for a person at any time.</p><span className="mic-ring"><Mic size={30}/></span><button className="widget-main-button" onClick={onPrimary}>Allow microphone & start <ArrowRight size={16}/></button><div className="widget-option"><Headphones size={17}/> Voice call with Website Support AI</div><Link className="widget-option" href={widgetPath(32)}><Phone size={17}/> Choose a callback instead</Link></>}
      {number===29&&<><div className="widget-wave"><AudioLines size={48}/><span>AI is listening</span></div><div className="widget-transcript"><span>AI voice agent</span><p>Welcome to Acme Support. What can I help you with?</p></div><div className="widget-question"><input value={form['Your question']||''} onChange={e=>update('Your question',e.target.value)} placeholder="Type a question to try the demo…"/><button disabled={typing} onClick={ask} aria-label="Ask voice agent"><Send size={17}/></button></div>{answer&&<div className="widget-transcript answer"><span>Website Support AI · Demo response</span><p>{answer}</p></div>}<button className="widget-main-button" onClick={onPrimary} disabled={working}>Talk to a person <ArrowRight size={16}/></button><div className="widget-call-controls"><button onClick={()=>setMuted(!muted)}><Mic size={18}/>{muted?'Unmute':'Mute'}</button><button onClick={()=>setMuted(!muted)}><Volume2 size={18}/> Audio</button><Link href={widgetPath(33)}><PhoneOff size={18}/> End call</Link></div></>}
      {number===30&&<><span className="connecting-orb"><Headphones size={38}/></span><p className="widget-description">A member of Technical Support has been notified. Please stay on the call.</p><div className="widget-progress"><span className="active">Requested</span><span className="active">Notifying team</span><span>Connecting</span></div><div className="widget-note"><Clock3 size={17}/> You're next in line. The AI has shared your question with the team.</div><button className="widget-main-button" onClick={onPrimary}>Check for available agent</button><Link className="widget-link" href={widgetPath(32)}>Request a callback instead</Link></>}
      {number===31&&<><div className="joined-avatars"><span><AudioLines size={22}/></span><span><UserRound size={23}/></span></div><h3>{record?.status==='human'?`${record?.data?.assignedAgent||'A support specialist'} is here to help`:'Waiting for an agent to join'}</h3><p className="widget-description">{record?.status==='human'?'Technical Support · You are now speaking with a person.':'An agent needs to accept this call before joining.'}</p><div className="widget-transcript"><span>System update</span><p>{record?.status==='human'?`${record?.data?.assignedAgent||'Your support specialist'} joined this conversation.`:'Your request has been sent to Technical Support.'}</p></div><div className="widget-call-controls"><button onClick={()=>setMuted(!muted)}><Mic size={18}/>{muted?'Unmute':'Mute'}</button><button><Volume2 size={18}/> Speaker</button><Link href={widgetPath(33)}><PhoneOff size={18}/> End call</Link></div></>}
      {number===32&&<><div className="callback-icon"><Phone size={26}/></div><p className="widget-description">No one is available right now. Leave your details and we’ll follow up.</p><div className="widget-form">{[['Your name','text'],['Phone number','tel'],['Email','email']].map(([label,type])=><label key={label}>{label}<input type={type} value={form[label]||''} onChange={e=>update(label,e.target.value)} required={label!=='Email'}/></label>)}<label>How can we help?<textarea value={form['How can we help?']||''} onChange={e=>update('How can we help?',e.target.value)}/></label></div><button className="widget-main-button" disabled={working||!form['Your name']||!form['Phone number']} onClick={onPrimary}>Request callback</button></>}
      {number===33&&<><span className="rating-orb"><Phone size={27}/></span><p className="widget-description">Your feedback helps us improve our support.</p><div className="widget-stars">{[1,2,3,4,5].map(value=><button key={value} aria-label={`Rate ${value} stars`} onClick={()=>{setStars(value);update('Rating',String(value))}}><Star size={29} fill={value<=stars?'#ffce56':'transparent'} color={value<=stars?'#ffce56':'#636080'}/></button>)}</div><textarea className="widget-feedback" placeholder="What went well? (optional)" value={form['Your feedback']||''} onChange={e=>update('Your feedback',e.target.value)}/><button className="widget-main-button" disabled={working} onClick={onPrimary}>Submit rating</button><Link href={widgetPath(28)} className="widget-link">Skip for now</Link></>}
      {number===42&&<><div className="widget-wave"><Phone size={39}/><span>Inbound phone route</span></div><p className="widget-description">A caller dials your business number. Website Support AI answers and can request a person.</p><button className="widget-main-button" onClick={onPrimary}>Open inbound routing <ArrowRight size={16}/></button></>}
    </div><div className="widget-footer">{feedback?<span className="widget-error" role="status">{feedback}</span>:<span><ShieldCheck size={14}/> Powered by ChatBucket Voice · Demo</span>}</div></section><Link className="customer-all-screens" href="/screens">View 51-screen flow</Link></div>;
}
