export const groups = [
  { name: 'Voice Agent creation', first: 1, last: 6 },
  { name: 'Voice Widget setup', first: 7, last: 12 },
  { name: 'Owner workspace', first: 13, last: 20 },
  { name: 'Human Agent workspace', first: 21, last: 27 },
  { name: 'Customer experience', first: 28, last: 33 },
  { name: 'Agent Studio & inbound', first: 34, last: 42 },
  { name: 'Outbound campaigns', first: 43, last: 51 },
];
const F = (label, type = 'text', options = []) => ({ label, type, options });
export const screens = {
  widgets: {
    reference: 7,
    storageKey: 'screen_7',
    group: 'Voice Widget setup',
    title: 'Voice Widgets',
    caption: 'Choose which voice agent answers calls on your website.',
    type: 'list',
    kind: 'widget',
    cta: 'Create voice widget',
    fields: [F('Widget name'), F('Voice agent', 'agent')],
    hints: [
      'A voice agent can be reused across multiple Voice Widgets.',
      'A widget is a separate web calling channel.',
    ],
  },
  'widget-appearance': {
    reference: 8,
    storageKey: 'screen_8',
    group: 'Voice Widget setup',
    title: 'Widget appearance',
    caption: 'Match your website’s voice button and call window.',
    type: 'setup',
    kind: 'widget',
    cta: 'Save appearance',
    fields: [
      F('Widget name'),
      F('Accent color', 'color'),
      F('Position', 'select', ['Bottom right', 'Bottom left']),
      F('Button label'),
      F('Launcher shape', 'select', ['Round', 'Pill']),
    ],
  },
  'widget-greeting': {
    reference: 9,
    storageKey: 'screen_9',
    group: 'Voice Widget setup',
    title: 'Greeting & caller details',
    caption: 'Decide what visitors hear and which details to collect.',
    type: 'setup',
    kind: 'widget',
    cta: 'Save greeting',
    fields: [
      F('Welcome message', 'textarea'),
      F('Ask for caller name', 'switch'),
      F('Ask for email', 'switch'),
      F('Ask for phone number', 'switch'),
      F('Privacy notice URL', 'url'),
    ],
  },
  'widget-handoff': {
    reference: 10,
    storageKey: 'screen_10',
    group: 'Voice Widget setup',
    title: 'Human handoff',
    caption: 'Route human requests to the right department.',
    type: 'setup',
    kind: 'widget',
    cta: 'Save handoff',
    fields: [
      F('Enable human support', 'switch'),
      F('Department', 'select', ['Technical Support', 'Sales', 'Customer Support']),
      F('Ring duration (seconds)', 'number'),
      F('After wait expires', 'select', ['Offer callback', 'Keep AI available', 'End politely']),
    ],
    hints: ['The AI stops speaking after a human accepts the call.'],
  },
  'widget-availability': {
    reference: 11,
    storageKey: 'screen_11',
    group: 'Voice Widget setup',
    title: 'Website, hours & fallback',
    caption: 'Choose where the widget appears and what happens after hours.',
    type: 'setup',
    kind: 'widget',
    cta: 'Save availability',
    fields: [
      F('Allowed website URL', 'url'),
      F('Time zone', 'select', ['Asia/Kolkata', 'UTC']),
      F('Open from', 'time'),
      F('Open until', 'time'),
      F('After-hours behavior', 'select', ['AI continues answering', 'Offer callback']),
      F('When agents are unavailable', 'select', ['Offer callback', 'Keep AI answering']),
    ],
  },
  'widget-publish': {
    reference: 12,
    storageKey: 'screen_12',
    group: 'Voice Widget setup',
    title: 'Test, install & publish',
    caption: 'Review your widget before adding it to a website.',
    type: 'setup',
    kind: 'widget',
    cta: 'Publish widget',
    publish: true,
    fields: [F('Widget name'), F('Allowed website URL', 'url')],
    hints: [
      'Install script is available after publishing.',
      'Publishing does not initiate a phone call.',
    ],
  },
  dashboard: {
    reference: 13,
    storageKey: 'screen_13',
    group: 'Owner workspace',
    title: 'Voice Operations Overview',
    caption: 'Real-time voice requests, agent activity and team performance.',
    type: 'dashboard',
    kind: 'call',
    cta: 'Open incoming requests',
    metrics: ['Active AI calls', 'Waiting for human', 'Live human calls', 'Callback requests'],
  },
  inbox: {
    reference: 14,
    storageKey: 'screen_14',
    group: 'Owner workspace',
    title: 'Incoming voice requests',
    caption: 'Customers waiting for a member of your team.',
    type: 'list',
    kind: 'call',
    cta: 'Review first waiting call',
    fields: [
      F('Caller name'),
      F('Issue summary', 'textarea'),
      F('Department', 'select', ['Technical Support', 'Sales', 'Customer Support']),
    ],
  },
  'live-calls': {
    reference: 15,
    storageKey: 'screen_15',
    group: 'Owner workspace',
    title: 'Live call monitoring',
    caption: 'See current calls and listen after gaining the correct permission.',
    type: 'dashboard',
    kind: 'call',
    cta: 'Open call monitor',
    metrics: ['Live AI calls', 'Live human calls', 'Waiting for agent', 'Longest wait'],
  },
  'call-takeover': {
    reference: 16,
    storageKey: 'screen_16',
    group: 'Owner workspace',
    title: 'Owner call takeover',
    caption: 'Take responsibility for a waiting or active call.',
    type: 'call',
    kind: 'call',
    cta: 'Take over call',
    transition: 'human',
    fields: [F('Takeover note', 'textarea')],
  },
  'call-history': {
    reference: 17,
    storageKey: 'screen_17',
    group: 'Owner workspace',
    title: 'Call history & transcript',
    caption: 'Review completed calls, summaries and conversation events.',
    type: 'list',
    kind: 'call',
    cta: 'View call details',
    fields: [F('Search caller'), F('Date', 'date')],
  },
  callbacks: {
    reference: 18,
    storageKey: 'screen_18',
    group: 'Owner workspace',
    title: 'Callback requests',
    caption: 'Follow up with customers who could not connect to a person.',
    type: 'list',
    kind: 'callback',
    cta: 'Assign callback',
    transition: 'assigned',
    fields: [
      F('Customer name'),
      F('Phone number', 'tel'),
      F('Reason', 'textarea'),
      F('Preferred time', 'datetime-local'),
    ],
  },
  reviews: {
    reference: 19,
    storageKey: 'screen_19',
    group: 'Owner workspace',
    title: 'Reviews & ratings',
    caption: 'Read caller feedback about voice conversations.',
    type: 'list',
    kind: 'rating',
    cta: 'View feedback',
    fields: [
      F('Search customer'),
      F('Rating', 'select', ['All', '5 stars', '4 stars', '3 stars', '2 stars', '1 star']),
    ],
  },
  transfers: {
    reference: 20,
    storageKey: 'screen_20',
    group: 'Owner workspace',
    title: 'Transfers',
    caption: 'Track active transfers and receiving agent acceptance.',
    type: 'list',
    kind: 'call',
    cta: 'Review transfer',
    fields: [
      F('Receiving department', 'select', ['Technical Support', 'Sales', 'Customer Support']),
    ],
  },
  'agent-inbox': {
    reference: 21,
    storageKey: 'screen_21',
    group: 'Human Agent workspace',
    title: 'Voice request inbox',
    caption: 'Human voice requests assigned to your department.',
    type: 'list',
    kind: 'call',
    cta: 'Review request',
    metrics: ['Waiting for you', 'My active calls', 'Completed today'],
  },
  'incoming-call': {
    reference: 22,
    storageKey: 'screen_22',
    group: 'Human Agent workspace',
    title: 'Incoming AI voice call',
    caption: 'A caller has asked the AI to connect with a human.',
    type: 'call',
    kind: 'call',
    cta: 'Review AI summary',
    hints: ['This notification is a handoff from the AI voice agent.'],
  },
  'call-review': {
    reference: 23,
    storageKey: 'screen_23',
    group: 'Human Agent workspace',
    title: 'AI summary & accept',
    caption: 'Read the reason for the call before joining.',
    type: 'call',
    kind: 'call',
    cta: 'Accept and join',
    transition: 'human',
    fields: [F('Internal note', 'textarea')],
  },
  'live-call': {
    reference: 24,
    storageKey: 'screen_24',
    group: 'Human Agent workspace',
    title: 'Live human call console',
    caption: 'Speak with the caller after accepting the handoff.',
    type: 'call',
    kind: 'call',
    cta: 'End call',
    transition: 'ended',
    fields: [F('Private team note', 'textarea')],
    hints: ['AI voice responses are paused while the human handles this call.'],
  },
  'transfer-call': {
    reference: 25,
    storageKey: 'screen_25',
    group: 'Human Agent workspace',
    title: 'Transfer live call',
    caption: 'Send the conversation and AI context to another agent.',
    type: 'call',
    kind: 'call',
    cta: 'Request transfer',
    transition: 'transfer-pending',
    fields: [
      F('Transfer to department', 'select', ['Technical Support', 'Sales', 'Customer Support']),
      F('Transfer to agent'),
      F('Reason for transfer', 'textarea'),
    ],
  },
  'accept-transfer': {
    reference: 26,
    storageKey: 'screen_26',
    group: 'Human Agent workspace',
    title: 'Accept transfer',
    caption: 'Review the current agent’s note and take ownership.',
    type: 'call',
    kind: 'call',
    cta: 'Accept transfer',
    transition: 'human',
    fields: [F('Receiving agent name')],
  },
  'call-outcome': {
    reference: 27,
    storageKey: 'screen_27',
    group: 'Human Agent workspace',
    title: 'Post-call outcome',
    caption: 'Record the result after the caller hangs up.',
    type: 'setup',
    kind: 'call',
    cta: 'Save outcome',
    fields: [
      F('Outcome', 'select', ['Resolved', 'Follow-up needed', 'Transferred']),
      F('Summary', 'textarea'),
      F('Follow-up time', 'datetime-local'),
    ],
  },
  'customer-call': {
    reference: 28,
    storageKey: 'screen_28',
    group: 'Customer experience',
    title: 'Call Acme Support',
    caption: 'Start a voice conversation from the website.',
    type: 'customer',
    kind: 'call',
    cta: 'Allow microphone',
    mic: true,
  },
  'ai-conversation': {
    reference: 29,
    storageKey: 'screen_29',
    group: 'Customer experience',
    title: 'Talk with the AI voice agent',
    caption: 'Ask your question or request a human.',
    type: 'customer',
    kind: 'call',
    cta: 'Request a person',
    fields: [F('Your question', 'textarea')],
  },
  connecting: {
    reference: 30,
    storageKey: 'screen_30',
    group: 'Customer experience',
    title: 'Connecting you to a person',
    caption: 'The AI is looking for an available team member.',
    type: 'customer',
    kind: 'call',
    cta: 'Stay in queue',
    hints: ['The caller hears a waiting message while human agents are notified.'],
  },
  'human-conversation': {
    reference: 31,
    storageKey: 'screen_31',
    group: 'Customer experience',
    title: 'Human agent joined',
    caption: 'A team member is now handling your conversation.',
    type: 'customer',
    kind: 'call',
    cta: 'Continue call',
    hints: ['Your agent’s name is shown when they accept.'],
  },
  'customer-callback': {
    reference: 32,
    storageKey: 'screen_32',
    group: 'Customer experience',
    title: 'All agents are unavailable',
    caption: 'Leave your details and the team can call you back.',
    type: 'customer',
    kind: 'callback',
    cta: 'Request callback',
    fields: [
      F('Your name'),
      F('Phone number', 'tel'),
      F('Email', 'email'),
      F('How can we help?', 'textarea'),
      F('Preferred time', 'datetime-local'),
    ],
  },
  'call-rating': {
    reference: 33,
    storageKey: 'screen_33',
    group: 'Customer experience',
    title: 'Rate your call',
    caption: 'Help improve the voice support experience.',
    type: 'customer',
    kind: 'rating',
    cta: 'Submit rating',
    fields: [F('Rating', 'select', ['5', '4', '3', '2', '1']), F('Your feedback', 'textarea')],
  },
  'agent-instructions': {
    reference: 34,
    storageKey: 'screen_34',
    group: 'Agent Studio & inbound',
    title: 'Agent instructions & prompt',
    caption: 'Define what the voice agent should do and how it should answer.',
    type: 'studio',
    kind: 'agent',
    cta: 'Save instructions',
    fields: [
      F('Voice agent', 'agent'),
      F('Agent instructions', 'textarea'),
      F('System prompt', 'textarea'),
      F('Variables', 'textarea'),
    ],
  },
  'agent-knowledge': {
    reference: 35,
    storageKey: 'screen_35',
    group: 'Agent Studio & inbound',
    title: 'Knowledge sources',
    caption: 'Manage the content your AI voice agent can use.',
    type: 'studio',
    kind: 'agent',
    cta: 'Save sources',
    fields: [
      F('Voice agent', 'agent'),
      F('Website URL', 'url'),
      F('FAQ question'),
      F('FAQ answer', 'textarea'),
      F('Demo source excerpt', 'textarea'),
    ],
    hints: [
      'Demo indexing stores only the text excerpt you provide. Website crawling and document processing require a retrieval service.',
    ],
  },
  'agent-actions': {
    reference: 36,
    storageKey: 'screen_36',
    group: 'Agent Studio & inbound',
    title: 'Actions & integrations',
    caption: 'Connect approved actions to your business systems.',
    type: 'studio',
    kind: 'agent',
    cta: 'Save action settings',
    fields: [
      F('Voice agent', 'agent'),
      F('Account lookup', 'switch'),
      F('Ticket creation', 'switch'),
      F('Endpoint URL', 'url'),
      F('Require confirmation', 'switch'),
    ],
    hints: ['An enabled action will not execute until its endpoint and credentials are verified.'],
  },
  'agent-advanced': {
    reference: 37,
    storageKey: 'screen_37',
    group: 'Agent Studio & inbound',
    title: 'Advanced voice behaviour',
    caption: 'Tune turn-taking, interruptions and fallback language.',
    type: 'studio',
    kind: 'agent',
    cta: 'Save behaviour',
    fields: [
      F('Voice agent', 'agent'),
      F('Speaking speed', 'select', ['Slow', 'Natural', 'Fast']),
      F('Allow caller interruptions', 'switch'),
      F('Silence prompt (seconds)', 'number'),
      F('Fallback language', 'select', ['English (India)', 'Hindi', 'Telugu']),
    ],
  },
  'agent-quality': {
    reference: 38,
    storageKey: 'screen_38',
    group: 'Agent Studio & inbound',
    title: 'Call data & quality rules',
    caption: 'Choose which call fields and quality checks are stored.',
    type: 'studio',
    kind: 'agent',
    cta: 'Save data rules',
    fields: [
      F('Voice agent', 'agent'),
      F('Collect caller consent', 'switch'),
      F('Save transcript', 'switch'),
      F('Save recording', 'switch'),
      F('Outcome categories', 'textarea'),
    ],
    hints: [
      'Recording and transcript retention need explicit privacy settings before live deployment.',
    ],
  },
  'agent-versions': {
    reference: 39,
    storageKey: 'screen_39',
    group: 'Agent Studio & inbound',
    title: 'Test, publish & versions',
    caption: 'Review agent changes before applying a published version.',
    type: 'studio',
    kind: 'agent',
    cta: 'Save draft version',
    fields: [F('Voice agent', 'agent'), F('Version note', 'textarea')],
    hints: ['A saved draft does not change the currently published voice agent.'],
  },
  'inbound-routing': {
    reference: 40,
    storageKey: 'screen_40',
    group: 'Agent Studio & inbound',
    title: 'Phone number & inbound routing',
    caption: 'Connect a business number and route inbound calls to an agent.',
    type: 'setup',
    kind: 'phone-route',
    cta: 'Save inbound route',
    fields: [
      F('Business phone number', 'tel'),
      F('Agent', 'agent'),
      F('Business hours', 'text'),
      F('After-hours behavior', 'select', ['AI answers', 'Offer callback']),
      F('Human handoff department', 'select', ['Technical Support', 'Sales', 'Customer Support']),
    ],
  },
  'agent-performance': {
    reference: 41,
    storageKey: 'screen_41',
    group: 'Agent Studio & inbound',
    title: 'Voice agent performance',
    caption: 'See outcomes and trends for one voice agent.',
    type: 'dashboard',
    kind: 'call',
    cta: 'View call history',
    metrics: ['Total calls', 'Resolved by AI', 'Human handoffs', 'Callback requests'],
  },
  'inbound-call': {
    reference: 42,
    storageKey: 'screen_42',
    group: 'Agent Studio & inbound',
    title: 'Inbound phone call',
    caption: 'Callers reach the AI agent through the connected business number.',
    type: 'customer',
    kind: 'call',
    cta: 'View inbound route',
    hints: ['An active telephony provider is required for real inbound calls.'],
  },
  campaigns: {
    reference: 43,
    storageKey: 'screen_43',
    group: 'Outbound campaigns',
    title: 'Outbound campaigns',
    caption: 'Plan and monitor AI voice campaigns.',
    type: 'list',
    kind: 'campaign',
    cta: 'Create campaign',
    fields: [F('Campaign name'), F('Agent', 'agent')],
  },
  'campaign-basics': {
    reference: 44,
    storageKey: 'screen_44',
    group: 'Outbound campaigns',
    title: 'Campaign basics & agent',
    caption: 'Choose the purpose and voice agent for outbound calls.',
    type: 'campaign',
    kind: 'campaign',
    cta: 'Save basics',
    fields: [
      F('Campaign name'),
      F('Purpose', 'textarea'),
      F('Voice agent', 'agent'),
      F('Opening script', 'textarea'),
    ],
  },
  'campaign-contacts': {
    reference: 45,
    storageKey: 'screen_45',
    group: 'Outbound campaigns',
    title: 'Contacts & eligibility',
    caption: 'Check opt-in, suppression and duplicates before dialing.',
    type: 'campaign',
    kind: 'campaign',
    cta: 'Save contacts',
    fields: [
      F('Contacts (one phone per line)', 'textarea'),
      F('Consent source'),
      F('Suppress opted-out contacts', 'switch'),
    ],
    hints: ['Real outbound dialing requires verified consent and suppression checks.'],
  },
  'campaign-calling-settings': {
    reference: 46,
    storageKey: 'screen_46',
    group: 'Outbound campaigns',
    title: 'Caller number & capacity',
    caption: 'Set the number shown to recipients and reserved inbound capacity.',
    type: 'campaign',
    kind: 'campaign',
    cta: 'Save calling settings',
    fields: [
      F('Verified caller number', 'tel'),
      F('Concurrent campaign calls', 'number'),
      F('Reserved inbound slots', 'number'),
      F('Calls per second', 'number'),
    ],
  },
  'campaign-schedule': {
    reference: 47,
    storageKey: 'screen_47',
    group: 'Outbound campaigns',
    title: 'Schedule, retries & voicemail',
    caption: 'Choose calling hours and safe retry settings.',
    type: 'campaign',
    kind: 'campaign',
    cta: 'Save schedule',
    fields: [
      F('Start date and time', 'datetime-local'),
      F('End date and time', 'datetime-local'),
      F('Time zone', 'select', ['Asia/Kolkata', 'UTC']),
      F('Maximum retries', 'number'),
      F('Voicemail action', 'select', ['Hang up', 'Leave approved short message']),
    ],
  },
  'campaign-review': {
    reference: 48,
    storageKey: 'screen_48',
    group: 'Outbound campaigns',
    title: 'Test, review & launch',
    caption: 'Check all campaign settings before starting calls.',
    type: 'campaign',
    kind: 'campaign',
    cta: 'Schedule campaign',
    transition: 'scheduled',
    hints: [
      'Scheduling stores the campaign. Real outbound calls require a configured dialer and verified number.',
    ],
  },
  'campaign-monitoring': {
    reference: 49,
    storageKey: 'screen_49',
    group: 'Outbound campaigns',
    title: 'Live campaign monitoring',
    caption: 'Watch call results as an outbound campaign runs.',
    type: 'dashboard',
    kind: 'campaign',
    cta: 'View current calls',
    metrics: ['Eligible contacts', 'Calls initiated', 'Connected', 'Queued'],
  },
  'outbound-handoff': {
    reference: 50,
    storageKey: 'screen_50',
    group: 'Outbound campaigns',
    title: 'Outbound AI-to-human handoff',
    caption: 'Join an outbound call after the AI requests help.',
    type: 'call',
    kind: 'call',
    cta: 'Accept handoff',
    transition: 'human',
    fields: [F('Handoff note', 'textarea')],
  },
  'campaign-results': {
    reference: 51,
    storageKey: 'screen_51',
    group: 'Outbound campaigns',
    title: 'Campaign results & call outcomes',
    caption: 'Review completions, connection rates and follow-ups.',
    type: 'dashboard',
    kind: 'campaign',
    cta: 'Back to campaigns',
    metrics: ['Contacts reached', 'AI completed', 'Human handoffs', 'Follow-ups'],
  },
};
