'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import { AudioLines, ArrowRight, CircleMinus, Clock3, Headphones, Phone, Sparkles, X } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { apiFetch } from './api-client';

export default function IncomingCallPopup({records,selected,onUpdate}){
  const router=useRouter();const [seconds,setSeconds]=useState(120);const [busy,setBusy]=useState(false);const [feedback,setFeedback]=useState('');
  const waiting=records.find(row=>row._id===selected?._id&&row.status==='waiting')||records.find(row=>row.status==='waiting');
  useEffect(()=>{const timer=setInterval(()=>setSeconds(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer)},[]);
  async function accept(){if(!waiting)return setFeedback('No waiting call is available.');setBusy(true);try{const response=await apiFetch(`/api/records/call/${waiting._id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'human',data:{assignedAgent:'Priya Sharma'}})});const value=await response.json();if(!response.ok)throw Error(value.error);localStorage.setItem('chatbucket:call',waiting._id);await onUpdate();router.push('/flow/24')}catch(error){setFeedback(error.message)}finally{setBusy(false)}}
  return <div className="popup-background"><div className="popup-calls"><h1>My Calls</h1><p>Handle your active and assigned calls.</p><div className="live-tabs"><strong>Active calls <small>{records.filter(r=>r.status==='human').length}</small></strong><span>Completed calls</span></div>{records.filter(r=>r.status==='human').map(item=><div className="popup-call-row" key={item._id}><span className="mini-avatar">{item.title[0]}</span><div><strong>{item.title}</strong><small>#{item._id.slice(-6).toUpperCase()} · Website voice call</small></div><i>● Live</i></div>)}</div><div className="incoming-popup" role="dialog" aria-label="Incoming call from AI Voice Agent"><header><span className="mini-avatar">AI</span><AudioLines size={25}/><div><strong>Incoming from AI Voice Agent</strong><p>Handoff to human agent</p></div><Link href="/flow/21" aria-label="Close popup"><X size={23}/></Link></header><div className="popup-caller"><span className="incoming-orb">{waiting?.title?.split(' ').map(s=>s[0]).slice(0,2).join('')||'—'}</span><div><h2>{waiting?.title||'No waiting request'}</h2><p>#{waiting?._id?.slice(-6).toUpperCase()||'—'} · Website voice call</p><small><Headphones size={14}/> {waiting?.data?.screen_14?.Department||'Technical Support'} &nbsp;·&nbsp; English (India)</small></div><span className="popup-timer"><Clock3 size={15}/> {String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')} <small>demo timer</small></span></div><div className="popup-issue"><strong>Issue</strong><p>{waiting?.data?.screen_14?.['Issue summary']||'Human assistance requested.'}</p></div><div className="popup-ai-summary"><Sparkles size={20}/><div><strong>AI summary</strong><p>Website Support AI has gathered the customer's request and notified your team. Review the details before accepting.</p></div></div>{feedback&&<p role="status" className="live-feedback">{feedback}</p>}<div className="popup-actions"><button onClick={accept} disabled={busy||!waiting}><Phone size={18}/> {busy?'Joining…':'Accept call'}</button><Link href="/flow/21"><CircleMinus size={18}/> Decline</Link></div><Link href="/flow/23" className="popup-review">Review details <ArrowRight size={16}/></Link></div></div>;
}
