'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,ArrowRight,CalendarDays,Check,Clock3,MapPin,Phone,PhoneIncoming,Search,ShieldCheck} from 'lucide-react';
import Shell from './Shell';
import {apiFetch} from './api-client';
const weekdays=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
function Field({label,children}){return <label className="nm-field">{label}{children}</label>}
export function NumberCatalog(){
 const [items,setItems]=useState([]),[owned,setOwned]=useState([]),[region,setRegion]=useState('All'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;Promise.all(['/api/numbers/catalog','/api/numbers'].map(url=>apiFetch(url))).then(async responses=>{const data=await Promise.all(responses.map(r=>r.json()));responses.forEach((r,i)=>{if(!r.ok)throw Error(data[i].error||'Could not load numbers.')});if(alive){setItems(data[0]);setOwned(data[1])}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[]);
 return <Shell active="/numbers"><div className="nm-page"><div className="nm-header"><div><span className="nm-kicker">INVENTORY / PHONE NUMBERS</span><h1>Phone numbers</h1><p>Choose a demo number, then prepare its voice agent and working hours.</p></div><span className="nm-tag">DEMO CATALOG</span></div>{owned.length>0&&<section className="nm-panel"><h2>Your demo reservations</h2><div className="nm-reservations">{owned.map(n=><Link key={n._id} href={`/numbers/${n._id}`}><Phone size={18}/><span><strong>{n.title}</strong><small>{n.data.region} · Routing draft</small></span><ArrowRight size={17}/></Link>)}</div></section>}<div className="nm-section"><div><h2>Browse available numbers</h2><p>Masked examples only. These numbers are not dialable or assigned by a carrier.</p></div><div className="nm-filter"><MapPin size={17}/><select aria-label="Filter by city" value={region} onChange={e=>setRegion(e.target.value)}>{['All',...new Set(items.map(i=>i.region))].map(v=><option key={v}>{v}</option>)}</select></div></div>{error&&<div className="nm-error" role="alert">{error}</div>}{loading?<div className="nm-panel">Loading catalog…</div>:<div className="nm-grid">{items.filter(item=>region==='All'||item.region===region).map(item=><div className="nm-card" key={item.id}><div className="nm-card-icon"><PhoneIncoming size={23}/></div><strong>{item.display}</strong><small>{item.region} · Area code {item.area}</small><div className="nm-card-bottom"><span className={item.available?'free':'held'}>{item.available?'Available in demo':'Reserved'}</span>{item.available?<Link href={`/numbers/review/${item.id}`} className="nm-secondary">Review <ArrowRight size={15}/></Link>:<span className="nm-muted">Unavailable</span>}</div></div>)}</div>}<p className="nm-footnote">No checkout, fee, KYC, telecom allocation, inbound routing, or payment occurs here. A provider must supply live inventory and pricing.</p></div></Shell>
}
export function NumberReview({catalogId}){
 const router=useRouter(),[item,setItem]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true;apiFetch('/api/numbers/catalog').then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'Could not load catalog.');if(alive)setItem(data.find(i=>i.id===catalogId)||null)}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[catalogId]);
 async function reserve(){setBusy(true);setError('');try{const r=await apiFetch('/api/numbers/reserve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({catalogId})});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not reserve demo number.');router.push(`/numbers/${data._id}`)}catch(e){setError(e.message);setBusy(false)}}
 return <Shell active="/numbers"><div className="nm-page nm-narrow"><Link href="/numbers" className="nm-back"><ArrowLeft size={16}/> Phone numbers</Link><span className="nm-kicker">NUMBER / REVIEW</span><h1>Review demo reservation</h1>{loading?<div className="nm-panel">Loading number…</div>:item?<div className="nm-panel nm-checkout"><span className="nm-card-icon"><Phone size={24}/></span><h2>{item.display}</h2><p>{item.region}, India · Area code {item.area}</p><div className="nm-review-row"><span>Reservation</span><strong>Demo record only</strong></div><div className="nm-review-row"><span>Payment</span><strong>None</strong></div><div className="nm-review-row"><span>Live inbound calls</span><strong>Unavailable</strong></div><div className="nm-warning"><ShieldCheck size={19}/><p>Confirm creates a reservation in this demo workspace. It does not buy, activate, or lease a real phone number.</p></div>{error&&<div className="nm-error" role="alert">{error}</div>}<div className="nm-actions"><Link href="/numbers" className="nm-secondary">Back to catalog</Link><button className="nm-primary" onClick={reserve} disabled={busy||!item.available}>{busy?'Reserving…':item.available?'Reserve demo number':'Already reserved'} <ArrowRight size={16}/></button></div></div>:<div className="nm-error">{error||'Number not found.'}</div>}</div></Shell>
}
export function NumberRouting({id}){
 const [record,setRecord]=useState(null),[form,setForm]=useState(null),[agents,setAgents]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let alive=true;Promise.all([apiFetch(`/api/numbers/${id}`),apiFetch('/api/voice-agents')]).then(async([a,b])=>{const [number,agents]=await Promise.all([a.json(),b.json()]);if(!a.ok)throw Error(number.error||'Could not load number.');if(!b.ok)throw Error(agents.error||'Could not load agents.');if(alive){setRecord(number);setForm(number.data.routing);setAgents(agents)}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[id]);
 function change(key,value){setForm(old=>({...old,[key]:value}));setNotice('')}
 async function save(){setBusy(true);setError('');setNotice('');try{const r=await apiFetch(`/api/numbers/${id}/routing`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:record.data.revision,routing:form})});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not save routing.');setRecord(data);setForm(data.data.routing);setNotice('Routing draft saved. This number is not live.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Shell active="/numbers"><div className="nm-page nm-narrow"><Link href="/numbers" className="nm-back"><ArrowLeft size={16}/> Phone numbers</Link>{loading?<div className="nm-panel">Loading routing…</div>:record&&form?<><div className="nm-header"><div><span className="nm-kicker">DEMO NUMBER / ROUTING DRAFT</span><h1>{record.title}</h1><p>{record.data.region} · Reserved in this demo workspace</p></div><span className="nm-tag">NOT ACTIVE</span></div><div className="nm-panel nm-routing"><div className="nm-section-title"><PhoneIncoming size={22}/><div><h2>Incoming calls</h2><p>Set which ready voice agent would answer when a provider is connected.</p></div></div><Field label="Voice agent"><select value={form.agentId||''} onChange={e=>change('agentId',e.target.value)}><option value="">Choose an agent</option>{agents.filter(a=>a.status==='ready').map(a=><option value={a._id} key={a._id}>{a.name}</option>)}</select></Field><div className="nm-section-title"><Clock3 size={22}/><div><h2>Working hours</h2><p>The voice agent should only be routed during these hours.</p></div></div><Field label="Time zone"><select value={form.timezone} onChange={e=>change('timezone',e.target.value)}>{['Asia/Kolkata','UTC','Europe/London','America/New_York'].map(v=><option key={v}>{v}</option>)}</select></Field><div className="nm-days">{weekdays.map(day=><label className={form.days.includes(day)?'active':''} key={day}><input type="checkbox" checked={form.days.includes(day)} onChange={e=>change('days',e.target.checked?[...form.days,day]:form.days.filter(d=>d!==day))}/>{day}</label>)}</div><div className="nm-time-row"><Field label="Start"><input type="time" value={form.start} onChange={e=>change('start',e.target.value)}/></Field><Field label="Stop"><input type="time" value={form.end} onChange={e=>change('end',e.target.value)}/></Field></div><Field label="Outside working hours"><select value={form.afterHours} onChange={e=>change('afterHours',e.target.value)}><option value="callback">Offer a callback</option><option value="end">End politely</option></select></Field>{error&&<div className="nm-error" role="alert">{error}</div>}{notice&&<div className="nm-success" role="status"><Check size={16}/>{notice}</div>}<div className="nm-actions"><button className="nm-primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save routing draft'}</button></div></div><div className="nm-warning"><ShieldCheck size={19}/><p>For live calls, connect a telephony provider, verify number ownership, configure carrier forwarding, and test concurrency and failover. <Link href="/routing/new" className="nm-inline-link">Plan an inbound route →</Link></p></div></>:<div className="nm-error">{error||'Number not found.'}</div>}</div></Shell>
}
