'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, Bell, CircleMinus, Clock3, Headphones, Info, Phone, Sparkles, UserRound, X } from 'lucide-react';
import { apiFetch } from './api-client';

export default function OutboundHandoff({records,selected,onSelect,onUpdate}){
  const router=useRouter();const [working,setWorking]=useState(false);const [message,setMessage]=useState('');
  const calls=records.filter(row=>row.data?.source==='campaign');
  const call=calls.find(row=>row._id===selected?._id&&row.status==='waiting')||calls.find(row=>row.status==='waiting')||calls[0];
  async function decide(accept){if(!call)return;setWorking(true);setMessage('');try{const response=await apiFetch(`/api/records/call/${call._id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:accept?'human':'ended',data:{...(accept?{assignedAgent:'Priya Sharma',aiPaused:true}:{outcome:'Declined by receiving agent'})}})});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to update the handoff');onSelect(data);await onUpdate();if(accept)router.push('/flow/24');else setMessage('You declined the handoff. The demo call was marked ended.')}catch(error){setMessage(error.message)}finally{setWorking(false)}}
  return <div className="handoff-page"><div className="handoff-inbox"><h1>Inbox</h1><p>Incoming calls, messages and handoff requests.</p><div className="handoff-tabs"><strong>All <span>{calls.filter(row=>row.status==='waiting').length}</span></strong><span>Voice handoffs</span><span>Messages</span></div>{calls.map(row=><button className={`handoff-inbox-item ${row._id===call?._id?'active':''}`} key={row._id} onClick={()=>onSelect(row)}><span className="handoff-avatar">{row.title.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><span><b>{row.title}</b><small>Outbound campaign handoff</small><small>{row.status==='waiting'?'Waiting for you':row.status}</small></span><em>{row.status==='waiting'?'● Live':'Completed'}</em></button>)}{!calls.length&&<div className="handoff-empty"><Bell size={30}/><strong>No campaign handoffs yet</strong><p>Run a scheduled demo campaign to simulate an AI request for a human.</p><Link className="button secondary" href="/flow/49">Campaign monitoring <ArrowRight size={16}/></Link></div>}</div>{call&&<aside className="handoff-popup"><header><span><Sparkles size={31}/></span><div><h2>Outbound campaign handoff — Sales Concierge AI</h2><p>September Renewal Outreach</p></div><Link href="/flow/21" aria-label="Close handoff"><X size={20}/></Link></header><div className="handoff-person"><span className="handoff-avatar large">{call.title.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><div><h2>{call.title}</h2><p>{call.data?.phone||'Phone number not supplied'}</p><p><Phone size={16}/> Live demo call · {call.data?.campaignId?.slice(-6)||'VC-3091'}</p></div><div className="handoff-timers"><strong><Clock3 size={19}/> 02:14</strong><small>sample call timer</small><strong><Bell size={19}/> Waiting</strong><small>for your response</small></div></div><div className="handoff-request"><p><Headphones size={18}/> Caller request</p><blockquote>“{call.data?.screen_14?.['Issue summary']||'I would like to speak with a person.'}”</blockquote></div><div className="handoff-context"><h3><Sparkles size={20}/> AI summary</h3><p>{call.data?.aiSummary||'The customer asked to speak with a human before making a decision.'}</p></div><div className="handoff-context"><h3><UserRound size={20}/> Contact details</h3><p>Source: Outbound campaign · Sales</p><p>{call.data?.phone||'Phone unavailable in this demo'}</p></div>{message&&<p className="flow-alert" role="status">{message}</p>}<div className="handoff-actions"><button className="button primary" disabled={working||call.status!=='waiting'} onClick={()=>decide(true)}><Phone size={19}/> Accept & join call</button><button className="button secondary" disabled={working||call.status!=='waiting'} onClick={()=>decide(false)}><CircleMinus size={19}/> Decline</button></div><p className="handoff-footnote"><Info size={17}/> AI is simulated until you accept; no actual phone connection is established.</p></aside>}</div>;
}
