'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,ArrowRight,CalendarClock,Check,ChevronRight,Clock3,GitBranch,PhoneForwarded,Play,Plus,Save,ShieldCheck,Signal,TriangleAlert} from 'lucide-react';
import Shell from './Shell';
import {apiFetch} from './api-client';
const weekdays=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
function Field({label,children,hint=''}){return <label className="rt-field">{label}{children}{hint&&<small>{hint}</small>}</label>}
function Alert({error,notice=''}){return <>{error&&<div className="rt-error" role="alert">{error}</div>}{notice&&<div className="rt-success" role="status"><Check size={16}/>{notice}</div>}</>}
export function RoutingList(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;apiFetch('/api/routing').then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'Could not load routes.');if(active)setRows(data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 return <Shell active="/routing"><div className="rt-page"><div className="rt-head"><div><span className="rt-kicker">DEPLOY / CALL ROUTING</span><h1>Call routing</h1><p>Plan where an incoming call goes during and outside your working hours.</p></div><Link className="rt-primary" href="/routing/new"><Plus size={17}/> New route</Link></div><div className="rt-intro"><PhoneForwarded size={25}/><span><strong>Existing business number?</strong><small>Set up a route and give the forwarding instructions to your telephony provider. This demo does not change carrier settings.</small></span></div><Alert error={error}/>{loading?<div className="rt-panel">Loading routes…</div>:rows.length?<div className="rt-list">{rows.map(row=><Link href={`/routing/${row._id}`} key={row._id}><span className="rt-icon"><GitBranch size={20}/></span><span><strong>{row.title}</strong><small>{row.data.numberLabel} · {row.data.source==='existing'?'Existing number':'Demo reservation'} · Draft</small></span><span className="rt-pill">Not live</span><ArrowRight size={17}/></Link>)}</div>:<div className="rt-empty"><GitBranch size={32}/><h2>No call routes</h2><p>Create a route, choose an agent, then preview office hours and after-hours behavior.</p><Link className="rt-primary" href="/routing/new">Create route</Link></div>}</div></Shell>
}
export function RoutingCreate(){
 const router=useRouter(),[name,setName]=useState(''),[source,setSource]=useState('existing'),[numberLabel,setNumberLabel]=useState(''),[numberId,setNumberId]=useState(''),[numbers,setNumbers]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{apiFetch('/api/numbers').then(r=>r.json()).then(data=>{if(Array.isArray(data))setNumbers(data)}).catch(()=>{})},[]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=await apiFetch('/api/routing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,source,numberLabel,numberId})});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not create route.');router.push(`/routing/${data._id}`)}catch(e){setError(e.message);setBusy(false)}}
 return <Shell active="/routing"><div className="rt-page rt-narrow"><Link href="/routing" className="rt-back"><ArrowLeft size={16}/> Call routing</Link><span className="rt-kicker">STEP 1 / NUMBER SOURCE</span><h1>New inbound route</h1><p className="rt-subtitle">Add a number you already own or select a masked demo reservation. Carrier forwarding needs separate confirmation.</p><form className="rt-panel" onSubmit={submit}><Field label="Route name"><input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Support line"/></Field><div className="rt-source"><button type="button" className={source==='existing'?'active':''} onClick={()=>setSource('existing')}><PhoneForwarded size={19}/><strong>Existing number</strong><small>Forward from your provider later</small></button><button type="button" className={source==='demo-number'?'active':''} onClick={()=>setSource('demo-number')}><Signal size={19}/><strong>Demo reservation</strong><small>Use a masked number for setup</small></button></div>{source==='existing'?<Field label="Business phone number" hint="E.164 format with country code, for example +919876543210. Ownership is not verified here."><input type="tel" value={numberLabel} onChange={e=>setNumberLabel(e.target.value)} placeholder="+919876543210"/></Field>:<Field label="Reserved demo number"><select value={numberId} onChange={e=>setNumberId(e.target.value)}><option value="">Choose reserved number</option>{numbers.map(n=><option key={n._id} value={n._id}>{n.title} · {n.data.region}</option>)}</select></Field>}<Alert error={error}/><div className="rt-actions"><button className="rt-primary" disabled={busy||!name.trim()}>{busy?'Creating…':'Create routing draft'} <ArrowRight size={16}/></button></div></form></div></Shell>
}
const tabs=[['overview','Overview'],['hours','Working hours'],['after-hours','After-hours'],['test','Sample call'],['capacity','Capacity'],['readiness','Launch checklist']];
function routeHref(id,view){return view==='overview'?`/routing/${id}`:`/routing/${id}/${view}`}
const localNow=()=>{const date=new Date();return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)};
export function RoutingDetail({id,view='overview'}){
 const router=useRouter(),[row,setRow]=useState(null),[form,setForm]=useState(null),[agents,setAgents]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[sampleAt,setSampleAt]=useState(localNow),[sample,setSample]=useState(null),[capacityInput,setCapacityInput]=useState({callsPerDay:1000,averageMinutes:3,busyHours:8,peakMultiplier:3}),[capacity,setCapacity]=useState(null),[readiness,setReadiness]=useState(null);
 useEffect(()=>{let active=true;Promise.all([apiFetch(`/api/routing/${id}`),apiFetch('/api/voice-agents')]).then(async([r,a])=>{const [route,agents]=await Promise.all([r.json(),a.json()]);if(!r.ok)throw Error(route.error||'Could not load route.');if(!a.ok)throw Error(agents.error||'Could not load agents.');if(active){setRow(route);setForm({name:route.title,config:route.data.config});setAgents(agents)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[id]);
 function change(key,value){setForm(old=>({...old,config:{...old.config,[key]:value}}));setDirty(true);setNotice('')}
 async function save(){if(!row||!form)return null;setBusy(true);setError('');try{const r=await apiFetch(`/api/routing/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:row.data.revision,...form})});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not save route.');setRow(data);setForm({name:data.title,config:data.data.config});setDirty(false);setNotice('Routing draft saved.');return data}catch(e){setError(e.message);return null}finally{setBusy(false)}}
 async function navigate(event,href){if(!dirty)return;event.preventDefault();if(await save())router.push(href)}
 async function action(type){setBusy(true);setError('');setNotice('');const current=dirty?await save():row;if(!current){setBusy(false);return}try{const path=type==='test'?'preview':type==='capacity'?'capacity':'readiness',method=type==='readiness'?'GET':'POST';const payload=type==='test'?{at:new Date(sampleAt).toISOString()}:capacityInput;const r=await apiFetch(`/api/routing/${id}/${path}`,{method,headers:{'Content-Type':'application/json'},...(method==='POST'?{body:JSON.stringify(payload)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not run check.');if(type==='test')setSample(data);if(type==='capacity')setCapacity(data);if(type==='readiness')setReadiness(data)}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(loading)return <Shell active="/routing"><div className="rt-page rt-panel">Loading route…</div></Shell>;
 if(!row||!form)return <Shell active="/routing"><div className="rt-page"><Link href="/routing" className="rt-back">← Call routing</Link><Alert error={error||'Route not found.'}/></div></Shell>;
 return <Shell active="/routing"><div className="rt-page"><Link href="/routing" onClick={e=>navigate(e,'/routing')} className="rt-back"><ArrowLeft size={16}/> Call routing</Link><div className="rt-head"><div><span className="rt-kicker">INBOUND ROUTE · DRAFT {dirty?'· UNSAVED':''}</span><h1>{row.title}</h1><p>{row.data.numberLabel} · {row.data.source==='existing'?'Existing number':'Masked demo number'} · Not live</p></div><button className="rt-secondary" disabled={busy||!dirty} onClick={()=>save()}><Save size={16}/>{busy?'Saving…':'Save draft'}</button></div><div className="rt-tabs">{tabs.map(([key,label])=><Link className={view===key?'active':''} key={key} href={routeHref(id,key)} onClick={e=>navigate(e,routeHref(id,key))}>{label}</Link>)}</div><Alert error={error} notice={notice}/>
 {view==='overview'&&<div className="rt-two"><section className="rt-panel"><h2>Call destination</h2><p className="rt-muted">Choose the voice agent that would answer during working hours.</p><Field label="Route name"><input maxLength={120} value={form.name} onChange={e=>{setForm(old=>({...old,name:e.target.value}));setDirty(true)}}/></Field><Field label="Ready voice agent"><select value={form.config.agentId} onChange={e=>change('agentId',e.target.value)}><option value="">Choose an agent</option>{agents.filter(agent=>agent.status==='ready').map(agent=><option key={agent._id} value={agent._id}>{agent.name}</option>)}</select></Field><div className="rt-actions"><button className="rt-primary" onClick={()=>save()} disabled={busy||!dirty}>Save destination</button></div></section><section className="rt-panel"><h2>Route summary</h2><div className="rt-facts"><span>Number</span><strong>{row.data.numberLabel}</strong><span>Hours</span><strong>{form.config.start}–{form.config.end} ({form.config.timezone})</strong><span>Closed action</span><strong>{form.config.afterHours==='callback'?'Offer callback':'End politely'}</strong></div><div className="rt-warning"><TriangleAlert size={19}/> Forwarding and streaming providers are not connected.</div><Link href={routeHref(id,'hours')} onClick={e=>navigate(e,routeHref(id,'hours'))} className="rt-secondary">Set working hours <ChevronRight size={16}/></Link></section></div>}
 {view==='hours'&&<div className="rt-panel rt-narrow"><div className="rt-section-title"><CalendarClock size={23}/><div><h2>Working hours</h2><p>Agent availability is evaluated in this time zone.</p></div></div><Field label="Time zone"><select value={form.config.timezone} onChange={e=>change('timezone',e.target.value)}>{['Asia/Kolkata','UTC','Europe/London','America/New_York'].map(z=><option key={z}>{z}</option>)}</select></Field><div className="rt-days">{weekdays.map(day=><label key={day} className={form.config.days.includes(day)?'active':''}><input type="checkbox" checked={form.config.days.includes(day)} onChange={e=>change('days',e.target.checked?[...form.config.days,day]:form.config.days.filter(d=>d!==day))}/>{day}</label>)}</div><div className="rt-time"><Field label="Start"><input type="time" value={form.config.start} onChange={e=>change('start',e.target.value)}/></Field><Field label="Stop"><input type="time" value={form.config.end} onChange={e=>change('end',e.target.value)}/></Field></div><Field label="Closed dates (one YYYY-MM-DD per line)" hint="At most 30 dates. These override the selected weekdays."><textarea rows={4} value={form.config.closedDates.join('\n')} onChange={e=>change('closedDates',e.target.value.split(/\s+/).filter(Boolean))} placeholder="2026-10-02"/></Field><button className="rt-primary" onClick={()=>save()} disabled={busy||!dirty}>Save hours</button></div>}
 {view==='after-hours'&&<div className="rt-panel rt-narrow"><div className="rt-section-title"><Clock3 size={23}/><div><h2>After-hours rules</h2><p>Define what a future call runtime should do when the route is closed.</p></div></div><div className="rt-choice"><button className={form.config.afterHours==='callback'?'active':''} onClick={()=>change('afterHours','callback')}>Offer callback</button><button className={form.config.afterHours==='end'?'active':''} onClick={()=>change('afterHours','end')}>End politely</button></div><Field label="Message to caller"><textarea rows={4} maxLength={300} value={form.config.afterHoursMessage} onChange={e=>change('afterHoursMessage',e.target.value)}/></Field><p className="rt-muted">This setting is saved as a draft. It does not place callbacks or control real calls.</p><button className="rt-primary" onClick={()=>save()} disabled={busy||!dirty}>Save after-hours rule</button></div>}
 {view==='test'&&<div className="rt-two"><section className="rt-panel"><div className="rt-section-title"><Play size={23}/><div><h2>Test a sample call</h2><p>Choose a time; no real call will be placed.</p></div></div><Field label="Sample date and time (your browser time zone)"><input type="datetime-local" value={sampleAt} onChange={e=>setSampleAt(e.target.value)}/></Field><button className="rt-primary" onClick={()=>action('test')} disabled={busy||!sampleAt}><Play size={16}/> {busy?'Testing…':'Preview route'}</button></section><section className="rt-panel"><h2>Decision</h2>{sample?<><span className="rt-pill">{sample.decision.replace(/-/g,' ')}</span><div className="rt-facts"><span>Local time</span><strong>{sample.weekday}, {sample.localDate} {sample.localTime}</strong><span>Time zone</span><strong>{sample.timeZone}</strong><span>Reason</span><strong>{sample.reason}</strong><span>During hours</span><strong>{sample.withinHours?'Yes':'No'}</strong></div><p className="rt-muted">Preview only. No provider call, timer or agent output executed.</p></>:<p className="rt-muted">Run a preview to see the exact path for this date and time.</p>}</section></div>}
 {view==='capacity'&&<div className="rt-two"><section className="rt-panel"><div className="rt-section-title"><Signal size={23}/><div><h2>Plan peak capacity</h2><p>Estimate simultaneous channels from a traffic scenario.</p></div></div>{[['callsPerDay','Calls per day'],['averageMinutes','Average call length (minutes)'],['busyHours','Busy hours per day'],['peakMultiplier','Peak multiplier']].map(([key,label])=><Field key={key} label={label}><input type="number" min={key==='averageMinutes'?.5:1} step={key==='averageMinutes'?.5:1} value={capacityInput[key]} onChange={e=>setCapacityInput(old=>({...old,[key]:e.target.value}))}/></Field>)}<button className="rt-primary" onClick={()=>action('capacity')} disabled={busy}>Estimate channels</button></section><section className="rt-panel"><h2>Planning result</h2>{capacity?<><div className="rt-capacity"><strong>{capacity.estimatedChannels}</strong><span>estimated channels for &lt;1% modeled blocking</span></div><div className="rt-facts"><span>Offered traffic</span><strong>{capacity.offeredLoad} Erlangs</strong><span>Estimated blocking</span><strong>{(capacity.blockingProbability*100).toFixed(2)}%</strong><span>Model</span><strong>{capacity.model}</strong></div><p className="rt-muted">{capacity.note}</p></>:<p className="rt-muted">Enter your peak assumptions to calculate an estimate. This does not purchase or reserve provider capacity.</p>}</section></div>}
 {view==='readiness'&&<div className="rt-panel rt-narrow"><div className="rt-section-title"><ShieldCheck size={23}/><div><h2>Launch checklist</h2><p>Review what is configured and which integrations still block live calls.</p></div></div><button className="rt-primary" disabled={busy} onClick={()=>action('readiness')}>{busy?'Checking…':'Run readiness check'}</button>{readiness&&<><div className="rt-checks">{readiness.checks.map(check=><div key={check.name}><span className={check.passed?'passed':'pending'}>{check.passed?<Check size={16}/>:<TriangleAlert size={16}/>}</span><span>{check.name}</span><strong>{check.passed?'Ready':'Pending'}</strong></div>)}</div><div className="rt-warning"><TriangleAlert size={18}/>{readiness.note}</div></>}<Link className="rt-secondary" href={routeHref(id,'test')}>Open sample test <ArrowRight size={15}/></Link></div>}
 </div></Shell>
}
