'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Info, Repeat2, Search, X } from 'lucide-react';
const teammates=[['Arjun Mehta','Technical Support','Online'],['Priya Sharma','Technical Support','Online'],['Karan Desai','Product Support','Away'],['Neha Verma','Customer Success','Offline']];
export default function TransferPanel({form,setForm,feedback,working,onTransfer}){
  const [query,setQuery]=useState('');const [validation,setValidation]=useState('');
  const update=(key,value)=>setForm(current=>({...current,[key]:value}));
  function submit(){if(!form['Transfer to agent']||!form['Reason for transfer']?.trim())return setValidation('Choose a teammate and enter a handoff reason.');setValidation('');onTransfer()}
  return <aside className="transfer-panel"><div className="transfer-panel-head"><h2><Repeat2 size={20}/> Transfer this call</h2><Link href="/flow/24" aria-label="Close transfer panel"><X size={20}/></Link></div><p>Find a teammate to hand off this demo call. The current agent remains assigned until acceptance.</p><label className="transfer-search">Search teammates<div><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or department"/></div></label><div className="teammate-list">{teammates.filter(([name,dept])=>`${name} ${dept}`.toLowerCase().includes(query.toLowerCase())).map(([name,dept,status])=><button key={name} disabled={status==='Offline'} className={form['Transfer to agent']===name?'selected':''} onClick={()=>{update('Transfer to agent',name);update('Transfer to department',dept)}}><span className="mini-avatar">{name.split(' ').map(word=>word[0]).join('')}</span><span><strong>{name}</strong><small>{dept}</small></span><em className={status.toLowerCase()}>● {status}</em><b>{form['Transfer to agent']===name?'●':'○'}</b></button>)}</div><label className="widget-setup-field">Transfer reason<textarea value={form['Reason for transfer']||''} onChange={e=>update('Reason for transfer',e.target.value)} placeholder="What does the next agent need to know?" rows={4}/></label>{(validation||feedback)&&<p role="status" className="live-feedback">{validation||feedback}</p>}<button className="button primary" disabled={working} onClick={submit}><Repeat2 size={17}/> {working?'Requesting…':'Request transfer'}</button><Link className="button secondary" href="/flow/24">Cancel</Link><p className="transfer-note"><Info size={16}/> AI stays silent while a person owns this demo conversation.</p></aside>;
}
