'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,ArrowRight,Check,Copy,Globe2,KeyRound,LockKeyhole,Plus,ShieldCheck,UserRound,PanelsTopLeft,Activity} from 'lucide-react';
import Shell from './Shell';
import {apiFetch} from './api-client';
function Field({label,children,hint}){return <label className="ws-field">{label}{children}{hint&&<small>{hint}</small>}</label>}
function Back({href='/widgets',children='Voice widgets'}){return <Link className="ws-back" href={href}><ArrowLeft size={16}/>{children}</Link>}
function Message({error,notice}){return <>{error&&<div role="alert" className="ws-error">{error}</div>}{notice&&<div role="status" className="ws-success"><Check size={16}/>{notice}</div>}</>}
function Tabs({id,view}){return <div className="ws-tabs">{[['domains','Domains'],['security','Session & publish'],['install','Install & activity']].map(([key,label])=><Link className={view===key?'active':''} href={`/widgets/${id}/${key}`} key={key}>{label}</Link>)}</div>}
function useWidget(id){const [row,setRow]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let active=true;apiFetch(`/api/widget-admin/widgets/${id}`).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'Could not load widget.');if(active)setRow(data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[id]);return {row,setRow,loading,error,setError}}
export function WorkspaceSettings(){
 const [profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;apiFetch('/api/widget-admin/profile').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load workspace.');if(active)setProfile(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 return <Shell active="/settings"><div className="ws-page"><span className="ws-kicker">WORKSPACE / SETTINGS</span><h1>Workspace settings</h1><p className="ws-subtitle">Business identity, website access, and member setup in one place.</p><Message error={error}/>{loading?<div className="ws-panel">Loading workspace…</div>:<><div className="ws-hero"><span className="ws-icon"><UserRound size={25}/></span><div><h2>{profile?.data?.companyName||'Your merchant workspace'}</h2><p>Support email: {profile?.data?.supportEmail||'Not set'} · {profile?.data?.timezone||'Asia/Kolkata'}</p></div><span className="ws-tag">DEMO</span></div><div className="ws-links"><Link href="/settings/profile"><UserRound size={22}/><span><strong>Merchant profile</strong><small>Company name, support email and time zone</small></span><ArrowRight size={18}/></Link><Link href="/widgets"><Globe2 size={22}/><span><strong>Voice widgets</strong><small>Verify domains and configure customer sessions</small></span><ArrowRight size={18}/></Link><Link href="/team"><ShieldCheck size={22}/><span><strong>Team</strong><small>Roles and availability</small></span><ArrowRight size={18}/></Link></div></>}</div></Shell>
}
export function MerchantProfile(){
 const [row,setRow]=useState(null),[form,setForm]=useState({companyName:'',supportEmail:'',timezone:'Asia/Kolkata'}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;apiFetch('/api/widget-admin/profile').then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'Could not load profile.');if(active){setRow(data);setForm({companyName:data.data.companyName||'',supportEmail:data.data.supportEmail||'',timezone:data.data.timezone||'Asia/Kolkata'})}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function save(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await apiFetch('/api/widget-admin/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,revision:row.data.revision})});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not save profile.');setRow(data);setNotice('Merchant profile saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Shell active="/settings"><div className="ws-page ws-narrow"><Back href="/settings">Workspace settings</Back><span className="ws-kicker">WORKSPACE / PROFILE</span><h1>Merchant profile</h1><p className="ws-subtitle">These details identify this demo workspace. Account registration and billing need production integrations.</p>{loading?<div className="ws-panel">Loading profile…</div>:<form className="ws-panel" onSubmit={save}><Field label="Company name"><input required maxLength={120} value={form.companyName} onChange={e=>setForm(f=>({...f,companyName:e.target.value}))}/></Field><Field label="Support email"><input type="email" required maxLength={180} value={form.supportEmail} onChange={e=>setForm(f=>({...f,supportEmail:e.target.value}))}/></Field><Field label="Time zone"><select value={form.timezone} onChange={e=>setForm(f=>({...f,timezone:e.target.value}))}>{['Asia/Kolkata','UTC','Europe/London','America/New_York'].map(z=><option key={z}>{z}</option>)}</select></Field><Message error={error} notice={notice}/><button className="ws-primary" disabled={busy}>{busy?'Saving…':'Save profile'}</button></form>}</div></Shell>
}
export function WidgetList(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;apiFetch('/api/widget-admin/widgets').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load widgets.');if(active)setRows(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 return <Shell active="/widgets"><div className="ws-page"><div className="ws-head"><div><span className="ws-kicker">BUILD / VOICE WIDGETS</span><h1>Voice widgets</h1><p>Connect a ready agent to verified websites. Customer sessions stay scoped to this widget.</p></div><Link className="ws-primary" href="/widgets/new"><Plus size={16}/> New widget</Link></div><Message error={error}/>{loading?<div className="ws-panel">Loading widgets…</div>:rows.length?<div className="ws-list">{rows.map(row=><Link key={row._id} href={`/widgets/${row._id}/domains`}><span className="ws-icon"><PanelsTopLeft size={20}/></span><span><strong>{row.title}</strong><small>{row.data.security?.domains?.filter(d=>d.status==='verified').length||0} verified domains · {row.status}</small></span><ArrowRight size={17}/></Link>)}</div>:<div className="ws-empty"><PanelsTopLeft size={32}/><h2>No widgets yet</h2><p>Add a widget, verify a domain and publish it.</p><Link className="ws-primary" href="/widgets/new">Create widget</Link></div>}<p className="ws-footnote">Legacy reference screens remain at /screens. Use this setup to publish a verified widget.</p></div></Shell>
}
export function WidgetCreate(){
 const router=useRouter(),[name,setName]=useState(''),[agentId,setAgentId]=useState(''),[agents,setAgents]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{apiFetch('/api/voice-agents').then(r=>r.json()).then(setAgents).catch(()=>setError('Could not load voice agents.'))},[]);
 async function create(e){e.preventDefault();setBusy(true);setError('');try{const r=await apiFetch('/api/widget-admin/widgets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,agentId})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not create widget.');router.push(`/widgets/${d._id}/domains`)}catch(e){setError(e.message);setBusy(false)}}
 return <Shell active="/widgets"><div className="ws-page ws-narrow"><Back/><span className="ws-kicker">WIDGET / CREATE</span><h1>Create voice widget</h1><form className="ws-panel" onSubmit={create}><span className="ws-icon"><PanelsTopLeft size={23}/></span><Field label="Widget name"><input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Customer support"/></Field><Field label="Ready voice agent"><select required value={agentId} onChange={e=>setAgentId(e.target.value)}><option value="">Choose agent</option>{Array.isArray(agents)&&agents.filter(a=>a.status==='ready').map(a=><option key={a._id} value={a._id}>{a.name}</option>)}</select></Field><Message error={error}/><button className="ws-primary" disabled={busy||!agentId}>{busy?'Creating…':'Create and verify domain'} <ArrowRight size={16}/></button></form></div></Shell>
}
export function WidgetDomains({id}){
 const {row,setRow,loading,error,setError}=useWidget(id),[origin,setOrigin]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function add(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await apiFetch(`/api/widget-admin/widgets/${id}/domains`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin,revision:row.data.security.revision})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not add domain.');setRow(d);setOrigin('');setNotice('Domain added. Verify its DNS TXT record next.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Shell active="/widgets"><div className="ws-page"><Back/><span className="ws-kicker">WIDGET / WEBSITE ACCESS</span><h1>{row?.title||'Widget'} · Domains</h1><p className="ws-subtitle">Only websites you prove ownership of can start a customer session.</p>{row&&<Tabs id={id} view="domains"/>}{loading?<div className="ws-panel">Loading domains…</div>:row?<div className="ws-grid"><section className="ws-panel"><h2>Allowed domains</h2>{row.data.security.domains.length?row.data.security.domains.map(d=><Link className="ws-domain" href={`/widgets/${id}/domains/${d.id}`} key={d.id}><Globe2 size={18}/><span><strong>{d.origin}</strong><small>{d.status==='verified'?'Verified on '+new Date(d.verifiedAt).toLocaleDateString('en-IN'):'Waiting for DNS verification'}</small></span><span className={`ws-state ${d.status}`}>{d.status}</span><ArrowRight size={16}/></Link>):<p className="ws-muted">No website domain has been added.</p>}</section><section className="ws-panel"><h2>Add a website</h2><p className="ws-muted">Enter the exact HTTPS origin used by your customers.</p><form onSubmit={add}><Field label="Website origin"><input type="url" required placeholder="https://shop.yourcompany.com" value={origin} onChange={e=>setOrigin(e.target.value)}/></Field><Message error={error} notice={notice}/><button className="ws-primary" disabled={busy}>{busy?'Adding…':'Add domain'} <Plus size={15}/></button></form></section></div>:<Message error={error}/>}</div></Shell>
}
export function WidgetVerify({id,domainId}){
 const {row,setRow,loading,error,setError}=useWidget(id),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[copied,setCopied]=useState(false);
 const domain=row?.data.security.domains.find(d=>d.id===domainId);
 async function verify(){setBusy(true);setError('');setNotice('');try{const r=await apiFetch(`/api/widget-admin/widgets/${id}/domains/${domainId}/verify`,{method:'POST'});const d=await r.json();if(!r.ok)throw Error(d.error||'Verification failed.');setRow(d);setNotice('Website ownership verified.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Shell active="/widgets"><div className="ws-page ws-narrow"><Back href={`/widgets/${id}/domains`}>Domains</Back><span className="ws-kicker">WIDGET / DOMAIN VERIFICATION</span><h1>Verify website</h1>{loading?<div className="ws-panel">Loading challenge…</div>:domain?<div className="ws-panel"><span className="ws-icon"><KeyRound size={22}/></span><h2>{domain.origin}</h2><p className="ws-muted">Add this TXT record to your domain DNS. DNS changes may take time to appear.</p><div className="ws-dns"><span>Type</span><strong>TXT</strong><span>Name</span><code>{domain.recordName}</code><span>Value</span><code>chatbucket-verify={domain.challenge}</code></div><button className="ws-secondary" onClick={()=>navigator.clipboard.writeText(`chatbucket-verify=${domain.challenge}`).then(()=>setCopied(true))}><Copy size={16}/>{copied?'Copied':'Copy value'}</button><Message error={error} notice={notice}/><div className="ws-actions"><button className="ws-primary" onClick={verify} disabled={busy}>{busy?'Checking DNS…':domain.status==='verified'?'Recheck DNS':'Check DNS record'}</button><Link className="ws-secondary" href={`/widgets/${id}/security`}>Session settings <ArrowRight size={16}/></Link></div></div>:<Message error={error||'Domain not found.'}/>}</div></Shell>
}
export function WidgetSecurity({id}){
 const {row,setRow,loading,error,setError}=useWidget(id),[minutes,setMinutes]=useState(15),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{if(row)setMinutes(row.data.security.sessionMinutes||15)},[row]);
 async function run(action){setBusy(true);setError('');setNotice('');try{const endpoint=action==='publish'?'publish':'security';const r=await apiFetch(`/api/widget-admin/widgets/${id}/${endpoint}`,{method:action==='publish'?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:row.data.security.revision,sessionMinutes:Number(minutes)})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not update widget.');setRow(d);setNotice(action==='publish'?'Widget published for verified domains.':'Session settings saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Shell active="/widgets"><div className="ws-page ws-narrow"><Back/><span className="ws-kicker">WIDGET / SESSION SECURITY</span><h1>{row?.title||'Widget'} · Security</h1>{row&&<Tabs id={id} view="security"/>}{loading?<div className="ws-panel">Loading settings…</div>:row?<div className="ws-panel"><span className="ws-icon"><LockKeyhole size={23}/></span><h2>Customer session</h2><p className="ws-muted">Each visitor gets a scoped, expiring token. The browser website origin must match a verified domain.</p><Field label="Session length (minutes)"><input type="number" min="5" max="60" value={minutes} onChange={e=>setMinutes(e.target.value)}/></Field><div className="ws-summary"><span>Verified domains</span><strong>{row.data.security.domains.filter(d=>d.status==='verified').length}</strong><span>Current status</span><strong>{row.status}</strong></div><Message error={error} notice={notice}/><div className="ws-actions"><button className="ws-secondary" disabled={busy} onClick={()=>run('save')}>Save policy</button><button className="ws-primary" disabled={busy||!row.data.security.domains.some(d=>d.status==='verified')} onClick={()=>run('publish')}><ShieldCheck size={16}/> Publish verified widget</button></div><p className="ws-footnote">Demo sessions remain in one API process. A production embed needs shared sessions, abuse controls, and a complete security review.</p></div>:<Message error={error}/>}</div></Shell>
}
export function WidgetInstall({id}){
 const {row,loading,error}=useWidget(id),[copied,setCopied]=useState(false),[counts,setCounts]=useState(null),[origin,setOrigin]=useState('');
 useEffect(()=>{setOrigin(window.location.origin);apiFetch('/api/records/call?limit=250').then(r=>r.json()).then(rows=>{if(Array.isArray(rows))setCounts(rows.filter(r=>r.data?.widgetId===id).length)}).catch(()=>{})},[id]);
 const snippet=`<script src="${origin}/chatbucket-voice.js" data-widget-id="${id}"></script>`;
 return <Shell active="/widgets"><div className="ws-page"><Back/><span className="ws-kicker">WIDGET / INSTALL & ACTIVITY</span><h1>{row?.title||'Widget'} · Install</h1>{row&&<Tabs id={id} view="install"/>}{loading?<div className="ws-panel">Loading installation…</div>:row?<div className="ws-grid"><section className="ws-panel"><h2>Website embed</h2><p className="ws-muted">Add this script to a verified website before the closing body tag.</p><pre className="ws-code"><code>{snippet}</code></pre><button className="ws-secondary" onClick={()=>navigator.clipboard.writeText(snippet).then(()=>setCopied(true))}><Copy size={16}/>{copied?'Copied':'Copy snippet'}</button><div className="ws-notice"><ShieldCheck size={18}/> {row.status==='published'?'This widget is published. Only verified origins can request sessions.':'Publish after DNS verification to open customer sessions.'}</div></section><section className="ws-panel"><h2>Demo activity</h2><div className="ws-summary"><span>Website sessions</span><strong>Not tracked in shared storage</strong><span>Widget demo calls</span><strong>{counts===null?'Loading…':counts}</strong><span>Verified domains</span><strong>{row.data.security.domains.filter(d=>d.status==='verified').length}</strong></div><p className="ws-footnote">Counts reflect only this demo API process. Live analytics require a durable event store.</p><Link className="ws-secondary" href="/ai-handoff"><Activity size={16}/> Review call queue</Link></section></div>:<Message error={error}/>}</div></Shell>
}
