'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Plus, Workflow, Search, ArrowRight, GitBranch} from 'lucide-react';
import Shell from './Shell';
import {apiFetch} from './api-client';
export default function WorkflowList(){
  const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('');
  useEffect(()=>{let active=true;apiFetch('/api/workflows').then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'Could not load workflows.');if(active)setItems(data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const visible=items.filter(item=>`${item.title} ${item.status}`.toLowerCase().includes(filter.toLowerCase()));
  return <Shell active="/workflows"><div className="wf-page"><div className="wf-heading"><div><p className="wf-eyebrow">BUILD / WORKFLOWS</p><h1>Workflows</h1><p>Map what happens before, during and after an AI voice conversation.</p></div><Link className="wf-primary" href="/workflows/new"><Plus size={18}/> Create workflow</Link></div><div className="wf-summary"><div><strong>{items.length}</strong><span>Total workflows</span></div><div><strong>{items.filter(x=>x.status==='published').length}</strong><span>Published</span></div><div><strong>{items.filter(x=>x.status==='draft').length}</strong><span>Drafts</span></div></div><div className="wf-search"><Search size={18}/><input aria-label="Search workflows" placeholder="Search workflows…" value={filter} onChange={e=>setFilter(e.target.value)}/></div>{error&&<p className="wf-error" role="alert">{error}</p>}{loading?<div className="wf-empty">Loading workflows…</div>:visible.length?<div className="wf-list">{visible.map(item=><Link key={item._id} href={`/workflows/${item._id}`} className="wf-list-row"><span className="wf-list-icon"><Workflow size={22}/></span><span className="wf-list-name"><strong>{item.title}</strong><small>{item.data?.draft?.trigger==='outbound'?'Outbound':'Inbound'} · {(item.data?.draft?.nodes||[]).length} nodes · Updated {new Date(item.updatedAt).toLocaleDateString('en-IN')}</small></span><span className={`wf-pill ${item.status}`}>{item.status==='published'?`Published v${item.data?.versions?.length||1}`:'Draft'}</span><ArrowRight size={19}/></Link>)}</div>:<div className="wf-empty"><GitBranch size={32}/><strong>{filter?'No matching workflows':'No workflows yet'}</strong><p>{filter?'Try another search.':'Create a flow to connect your voice agent, decisions and call outcome.'}</p>{!filter&&<Link className="wf-primary" href="/workflows/new">Create first workflow</Link>}</div>}<p className="wf-demo-note">Preview mode: workflow tests do not place phone calls or execute external tools.</p></div></Shell>
}
